### ISSUE TITLE
Allow using proxy server

### ISSUE THREAD

**Issue by Fungus-00** [retorquere/zotero-deb#102]
`install.sh` uses `sudo curl ...` etc. to download the `gpg` file, making it unable to utilize the `https_proxy` environment variable in shell, without which I cannot access certain network. Therefore, I advise to change it to `sudo -E curl ...` so that the system proxy server can be inherited. And what's more, one should be reminded to take more actions in `README.md` if he/she uses proxy.

**Comment by retorquere** [comment]
> And what's more, one should be reminded to take more actions in README.md if he/she uses proxy.

Such as? Pointing this out will elicit questions, and I have no idea where I would start.
