### ISSUE TITLE
Adding your repo to Extrepo

### ISSUE THREAD

**Issue by n-peugnet** [retorquere/zotero-deb#104]
Hello, I took the initiative to add your repo to [Extrepo](https://salsa.debian.org/extrepo-team/extrepo), a tool that helps configuring external repositories on Debian in a secure manner. I hope you don't mind.

Here is the merge request on extrepo-data: https://salsa.debian.org/extrepo-team/extrepo-data/-/merge_requests/290

**Comment by retorquere** [comment]
Ah, cool. That looks like a great way to install.

**Comment by n-peugnet** [comment]
I think so too, with extrepo installed it can be enabled with:

    sudo extrepo enable zotero

Then zotero can be installed as usual:

    sudo apt update
    sudo apt install zotero

And if the URL or the GPG key has changed, once updated in the extrepo-data repository, it can be easily updated with:

    sudo extrepo update zotero

------ 


By the way, I saw that you intended to maybe transfer the repo soon, could you ping me here when you do so I can update it on extrepo-data, or even better, submit the merge request yourself :)

**Comment by retorquere** [comment]
That plan has existed for years; it doesn't seem to be a priority for the zotero team, and it's zero-maintenence for me at this point.
