### ISSUE TITLE
Upstreaming to Debian Repos

### ISSUE THREAD

**Issue by joseph-finger** [retorquere/zotero-deb#107]
Dear @retorquere 
have you ever considered upstreaming your package to the debian repos ? This way the package would be available on Debian, Ubuntu, Mint, PopOS etc. natively.
Or is there a specific reason you're avoiding them (the debian repos), I am unaware of ?
Cheers,
Joseph

**Comment by retorquere** [comment]
Not possible unfortunately: #84

**Comment by joseph-finger** [comment]
Wups didnt see that !
Thank you very very much

**Comment by retorquere** [comment]
No worries. I've pinned that issue to make it easier to find.
