### ISSUE TITLE
Not installable in Debian Sid

### ISSUE THREAD

**Issue by Doc73** [retorquere/zotero-deb#110]
Dear dev,
Zotero is not installable in Debian Sid due to the lack of `libgdk-pixbuf2.0-0` library, still available only on debports: [https://packages.debian.org/sid/libgdk-pixbuf2.0-0](https://packages.debian.org/sid/libgdk-pixbuf2.0-0).

As I see, `libgdk-pixbuf2.0-0` is only a transitional package for `libgdk-pixbuf-2.0-0`
(cf. [https://packages.debian.org/bookworm/libgdk-pixbuf2.0-0](https://packages.debian.org/bookworm/libgdk-pixbuf2.0-0)

```
$ apt search libgdk-pixbuf
libg3d-plugin-gdkpixbuf/unstable,testing 0.0.8-37+b2 amd64
  plugin for the LibG3D library

libgdk-pixbuf-2.0-0/unstable,testing,now 2.42.12+dfsg-1+b1 amd64 [installed]
  GDK Pixbuf library

libgdk-pixbuf-2.0-dev/unstable,testing 2.42.12+dfsg-1+b1 amd64
  GDK Pixbuf library (development files)

libgdk-pixbuf-xlib-2.0-0/unstable,testing,now 2.40.2-4 amd64 [installed]
  GDK Pixbuf library (deprecated Xlib integration)

libgdk-pixbuf-xlib-2.0-dev/unstable,testing 2.40.2-4 amd64
  GDK Pixbuf library (development files)

libgdk-pixbuf2.0-bin/unstable,testing,now 2.42.12+dfsg-1+b1 amd64 [installed,automatic]
  GDK Pixbuf library (thumbnailer)

libgdk-pixbuf2.0-common/unstable,testing,now 2.42.12+dfsg-1 all [installed,automatic]
  GDK Pixbuf library - data files

libgdk-pixbuf2.0-doc/unstable,testing 2.42.12+dfsg-1 all
  GDK Pixbuf library (documentation)
```

For now I solved it by downloading the package from another site

**Comment by retorquere** [comment]
New builds are running, should be available in 15 minutes.
