### ISSUE TITLE
Unclear how to update Zotero as packaged by zotero-deb

### ISSUE THREAD

**Issue by ngirard** [retorquere/zotero-deb#12]
It is unclear how Zotero as packaged by zotero-deb is to be updated.

Is Zotero's own self-update facility still enabled ? If so, is it the preferred way of updating Zotero, rather than updating the `.deb` package ? Is there any conflicts between both systems ?

**Comment by retorquere** [comment]
You'd update as you would always update `.deb` packaged programs -- `apt`/`apt-get` most of the time, re-install using `dpkg` if you're on a Chromebook. The self-update facility of Zotero is disabled in this package, but it wouldn't work anyway, as the files as installed are `root`-owned, and at the time Zotero could self-update, it usually isn't (really shouldn't) run as `root`.

**Comment by retorquere** [comment]
You can safely have both Zotero installed from this `.deb` and just as it is unpacked from the tarball if you want, but it's not safe to update the files as this `.deb` installs them in `/usr/lib/zotero`.

**Comment by ngirard** [comment]
Thanks for your explanations !

I've just opened PR #13, taking them into account.
