### ISSUE TITLE
Application not discovered in search

### ISSUE THREAD

**Issue by rcragun** [retorquere/zotero-deb#16]
Reproduce:

- Install Zotero from the PPA on Ubuntu 18.04.
- Hit "Show Applications". Zotero will show up.
- Type "Zotero". Zotero will not show up.

**Comment by retorquere** [comment]
When you say PPA, you mean the repo hosted in this github project yes? I'm asking because this isn't technically a PPA, and there is a PPA for Zotero that is not maintained by me.

**Comment by retorquere** [comment]
For me, Zotero does show up when I type. Is there anything in a system log about this? Is Zotero listed when you do `dpkg -l | grep zotero`? What does `which zotero` say?

**Comment by retorquere** [comment]
And do you have any shell extensions installed?

**Comment by ngirard** [comment]
I've just installed Zotero on a 18.10 Ubuntu system, and I confirm it does show up in the applications menu.

**Comment by retorquere** [comment]
@rcragun I'll need more info from you.

**Comment by rcragun** [comment]
By "PPA", I meant the repository for this project. I am not proficient with the terminology. Zotero is listed by `dpkg -l`, and `which zotero` returns `/usr/local/bin/zotero`. I have no gnome shell extensions installed (unless changing the middle click on titlebar action in Tweaks counts as an "extension"--again, I am not proficient with the terminology). 

Given that others cannot reproduce this, it is probably a results of failed attempts I made to install Zotero from the developer's tarball.

**Comment by retorquere** [comment]
I don't know -- shouldn't do much harm. Do you have the `locate` database updated? What does `locate zotero.desktop` say?

**Comment by rcragun** [comment]
How would I know if I have the `locate` database updated? I ran `updatedb`, and that did not change the behavior. `locate zoteo.desktop` returns 

```
/home/randy/.local/share/applications/zotero.desktop
/usr/share/applications/zotero.desktop
```

I just noticed that in "Show Applications" Zotero shows up in the "Frequent" list but not in the "All" list. @ngirard, do you observe the same behavior for 18.10?

**Comment by retorquere** [comment]
That should do it. It could be that /home/randy/.local/share/applications/zotero.desktop` points to a missing dir, which would mess things up; it's also not needed if you have the deb installed.

Can you remove `/home/randy/.local/share/applications/zotero.desktop` and [restart gnome shell](https://unix.stackexchange.com/questions/12118/how-do-i-refresh-gnome-3-applications) (or just restart if you prefer) and see if things improve?

**Comment by retorquere** [comment]
For me, Zotero shows up in both all and frequent. I'm on 19.04 though.

**Comment by rcragun** [comment]
That worked. I know that fixing whatever was wrong on my system mat not have been related to any bug in this project, so I really appreciate the help.

**Comment by retorquere** [comment]
Very welcome.

**Comment by ngirard** [comment]
@rcragun glad you could solve your problem.

It would be nice if you could amend your comment on [Ask Ubuntu](https://askubuntu.com/questions/332109/how-to-install-zotero-in-ubuntu/1160369?noredirect=1#comment1938829_1160369), so that newcomers are not confused.

**Comment by rcragun** [comment]
Good point. Done.
