### ISSUE TITLE
Automatic update not disabled

### ISSUE THREAD

**Issue by ngirard** [retorquere/zotero-deb#17]
Every 24h, Zotero pops up a window complaining a new version is available and that the update cannot be performed.
So it seems like Zotero's automatic system is not disabled.

**Comment by retorquere** [comment]
I'm looking into it.

**Comment by retorquere** [comment]
The new update should fix it

**Comment by ngirard** [comment]
Great thanks, I've installed it. I'll let you know about the outcome soon !

**Comment by retorquere** [comment]
Easy to verify -- if you go into hidden preferences, `app.update.enabled` and `app.update.auto` should be `false` now.

**Comment by ngirard** [comment]
Well then, we're set ! Thanks for your efforts !

**Comment by retorquere** [comment]
You're welcome, and thanks for reporting
