### ISSUE TITLE
Application / package version mismatch

### ISSUE THREAD

**Issue by ngirard** [retorquere/zotero-deb#19]
The package I've installed has version 5.0.74, but once started, Zotero says its version is 5.0.71.

**Comment by retorquere** [comment]
It doesn't for me. If you type `which zotero`, it should say `/usr/local/bin/zotero`. If you type `/usr/local/bin/zotero` on the command line, and check the version, it should say 5.0.74. Assuming that `dpkg -l | grep zotero`

shows

```
ii  zotero                                                      5.0.74                                                      amd64        Zotero is a free, easy-to-use tool to help you collect, organize, cite, and share research
```

**Comment by ngirard** [comment]
Sorry for the noise. I think I had a ghost living instance of Zotero, which hadn't been restarted in a while ; and I didn't see it because of this damnit Kwin window manager that I have to kill & restart every now and then. Oh well.

**Comment by retorquere** [comment]
no worries.
