### ISSUE TITLE
Check for ARM architecture when adding repo

### ISSUE THREAD

**Issue by adam3smith** [retorquere/zotero-deb#20]
Cross-posted with https://forums.zotero.org/discussion/78641/step-by-step-instructions-for-installing-zotero-standalone-on-chrome-os-chromebook#latest

Now that more Chromebook users are trying to use this to install Zotero, it'd be super helpful to implement a check (presumbaly via `uname - m`?) for the architecture before adding the repo to sources.list.d and produce a more meaningful error in the terminal for ARM machines.

**Comment by retorquere** [comment]
Do you happen to know what 32 bit linux returns for that? I know 64 bit returns `x86_64`. I'd rather test for positives than negatives.

**Comment by retorquere** [comment]
I've updated `install.sh`

**Comment by adam3smith** [comment]
I think it can technically also be i386 but given that that is < Pentium II,  not sure how many of those there are around ;) I do think Zotero runs on them, though, so can't hurt to include.

**Comment by retorquere** [comment]
done
