### ISSUE TITLE
XPCOMGlueLoad error when starting Zotero 5.0.81

### ISSUE THREAD

**Issue by ngirard** [retorquere/zotero-deb#21]
Hey Emiliano, happy new year,

After updating Zotero from 5.0.77 to 5.0.81 on Ubuntu 19.04, I'm getting the following error when starting Zotero:
```sh
XPCOMGlueLoad error for file /usr/lib/zotero/libxul.so:
/usr/lib/zotero/libxul.so: undefined symbol: _ZN7mozilla11SandboxInfo14ThreadingCheckEv
Couldn't load XPCOM.
```

Cheers!

**Comment by retorquere** [comment]
Thank you. 

I can't do anything about this, sorry. I just repackage Zotero without any changes, you'll have to report this to Zotero itself.

**Comment by ngirard** [comment]
Sure, will do. I'll report back here afterwards.

**Comment by ngirard** [comment]
Meanwhile, can I downgrade to some previous version ? Verifying if the error arises using previous versions might help upstream, and besides, I need a working Zotero for my daily work...

apt downloaded the package from `https://github.com/retorquere/zotero-deb/releases/download/global-menu/zotero_5.0.81_amd64.deb`, but there doesn't seem to be such `https://github.com/retorquere/zotero-deb/releases/download/global-menu/zotero_5.0.80_amd64.deb` file.

**Comment by ngirard** [comment]
See https://forums.zotero.org/discussion/80965/xpcomglueload-error-when-starting-zotero-5-0-81 for the ongoing discussion with Dan.

**Comment by retorquere** [comment]
I don't have older versions in the repo. They should be easy to rebuild, I'll give that a shot.

**Comment by retorquere** [comment]
You have the `global-menu` version. Zotero recently upgraded the Firefox it builds on, and the global-menu patches no longer work for it. I recommend you uninstall zotero and run the full

```
wget -qO- https://github.com/retorquere/zotero-deb/releases/download/apt-get/install.sh | sudo bash
sudo apt update
sudo apt install zotero
```

to get the standard Zotero.

**Comment by ngirard** [comment]
> You have the global-menu version.

I'm for sure willing to use the "regular" flavor instead, but IMHO that doesn't explain everything: on my laptop I've also installed the "global menu" version and it starts just fine.

Anyway, I'll perform the re-installation tonight and report back afterwards. Cheers !

**Comment by retorquere** [comment]
That the global-menu version still works is harder to explain than that it doesn't. Global-menu uses a custom libxul.so that was compiled for Firefox ESR52. Zotero 5.0.81 (and a few versions before that) were built on ESR60. I didn't compile that version, someone contributed it, and that person hasn't yet responded on my question whether (s)he'll provide an updated version.

With such being the case, the global-menu version is not in a state that anyone can support it. If the global-menu version does come back, I'm going to mark it clearly as such.
