### ISSUE TITLE
Why is global-menu disabled?

### ISSUE THREAD

**Issue by kupiqu** [retorquere/zotero-deb#22]
Thank you for the good work, very much appreciated!

But I wonder why I can't use global menu in Zotero as I do in all my other applications (including Firefox).

**Comment by retorquere** [comment]
The global menu version used a patched binary of Zotero (of libxul to be precise), and the person who provided the patched binary hasn't responded after Zotero upgraded to FF60. The libxul I was provided with no longer works with FF60.

It also made diagnosis more problematic for Zotero. If Zotero releases a global-menu version, I will be happy to provide it as a deb.

**Comment by kupiqu** [comment]
I see, thank you for the information
