### ISSUE TITLE
Which Port should I use?

### ISSUE THREAD

**Issue by nathan-nz** [retorquere/zotero-deb#25]
Hey, thanks for hosting this awesome depository - I've got Zotero on my Chromebook now and couldn't be happier.

I had a little trouble getting it to work when following https://github.com/retorquere/zotero-deb/wiki - but got there in the end. 

What I did different that worked (but stumped me for a while)

1. I made the rule in Connection Forwarder 127.0.0.1:23119-->127.0.0.1:8080
     - for some reason this didn't work from 0.0.0.0:23119
     - this had to be done with Crostini _closed_ or I got an error saying:
![Screenshot 2020-05-02 at 07 12 48](https://user-images.githubusercontent.com/63566309/80857159-fc611480-8ca3-11ea-850c-57c13602b087.png)
1. In Zotero running in Crostini, the Config editor wouldn't accept text input. No idea why - my arrow keys worked fine. It would accept cutting and pasting, which got me there.

Now working just great. Thanks again!!

**Comment by retorquere** [comment]
I'm sorry, I can't help with this -- I don't own a chromebook myself. I use the debs on Linux. I copied the Wiki instructions from the Zotero forums as it seemed handy to have them easy to find, but I haven't followed this process myself.

**Comment by nathan-nz** [comment]
No probs - like I said I worked it out. I can't edit your wiki to add this bit though.

**Comment by retorquere** [comment]
That was unintentional -- you should be able to edit now.

**Comment by nathan-nz** [comment]
Sweet - have done so!
