### ISSUE TITLE
Errors in zotero.desktop file?

### ISSUE THREAD

**Issue by Jakethethird** [retorquere/zotero-deb#26]
Hello, 
When installing another deb package (zoom) in Ubuntu 20.04, I get these error messages about the zotero.desktop file when it runs a post install script. Are they significant? I've been ignoring them, but wonder if the file is somehow misconfigured.

Thanks, 
Jake

ps Thanks for this project - Zotero is so easy to install and manage like this.

```

bob@bobpc:~$ sudo dpkg -i /tmp/zoom.deb
[sudo] password for bob: 
(Reading database ... 243519 files and directories currently installed.)
Preparing to unpack /tmp/zoom.deb ...
Unpacking zoom (5.0.418682.0603) over (5.0.418682.0603) ...
run post uninstall script, action is upgrade ...
Setting up zoom (5.0.418682.0603) ...
run post install script, action is configure...
Error in file "/usr/share/applications/zotero.desktop": "ris" is an invalid MIME type ("ris" does not contain a subtype)
Error in file "/usr/share/applications/zotero.desktop": "text/application/x-research-info-systems" is an invalid MIME type ("text/application/x-research-info-systems" contains an invalid character in the subtype)
Error in file "/usr/share/applications/zotero.desktop": "ciw" is an invalid MIME type ("ciw" does not contain a subtype)
Error in file "/usr/share/applications/zotero.desktop": "isi" is an invalid MIME type ("isi" does not contain a subtype)
Error in file "/usr/share/applications/zotero.desktop": "mods" is an invalid MIME type ("mods" does not contain a subtype)
Error in file "/usr/share/applications/zotero.desktop": "rdf" is an invalid MIME type ("rdf" does not contain a subtype)
Error in file "/usr/share/applications/zotero.desktop": "bib" is an invalid MIME type ("bib" does not contain a subtype)
Error in file "/usr/share/applications/zotero.desktop": "bibtex" is an invalid MIME type ("bibtex" does not contain a subtype)
Error in file "/usr/share/applications/zotero.desktop": "mrc" is an invalid MIME type ("mrc" does not contain a subtype)
Error in file "/usr/share/applications/zotero.desktop": "marc" is an invalid MIME type ("marc" does not contain a subtype)
Error in file "/usr/share/applications/zotero.desktop": "csl" is an invalid MIME type ("csl" does not contain a subtype)
Error in file "/usr/share/applications/zotero.desktop": "vnd.citationstyles.style+xml" is an invalid MIME type ("vnd.citationstyles.style+xml" does not contain a subtype)
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for shared-mime-info (1.15-1) ...
bob@bobpc:~$ 
```

**Comment by retorquere** [comment]
Won't cause problems but it was an error. I've pushed pushed out a patch.

**Comment by Jakethethird** [comment]
Hi, 
Much better - don't get the long list of errors, but there are two stubborn ones remaining.

Jake.

bob@bobpc:~$ sudo dpkg -i /tmp/zoom.deb
(Reading database ... 243519 files and directories currently installed.)
Preparing to unpack /tmp/zoom.deb ...
Unpacking zoom (5.0.418682.0603) over (5.0.418682.0603) ...
run post uninstall script, action is upgrade ...
Setting up zoom (5.0.418682.0603) ...
run post install script, action is configure...
Error in file "/usr/share/applications/zotero.desktop": "text/application/x-research-info-systems" is an invalid MIME type ("text/application/x-research-info-systems" contains an invalid character in the subtype)
Error in file "/usr/share/applications/zotero.desktop": "vnd.citationstyles.style+xml" is an invalid MIME type ("vnd.citationstyles.style+xml" does not contain a subtype)
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for shared-mime-info (1.15-1) ...

**Comment by retorquere** [comment]
I bumped the version, those errors should be gone now too.

**Comment by Jakethethird** [comment]
Yes, it's fixed now. No errors.
Thanks!
