### ISSUE TITLE
Chromebook wiki says Zotero will be in Linux apps folder, for me it's with all other apps

### ISSUE THREAD

**Issue by MaxGhenis** [retorquere/zotero-deb#28]
Thank you for building this! I've been wanting to use Zotero on my chromebook for a while.

Step 3 of the [wiki](https://github.com/retorquere/zotero-deb/wiki) says:

>Once those finish, you can close the Terminal and go back to the Linux apps folder. You will now see an icon for Zotero, and clicking on it will open the app, as normal. You can then pin the app to your Chrome Launcher.

I didn't see a Linux apps folder on my machine, but Zotero was in the list of all Chromebook apps.

I'm on a Pixelbook, ChromeOS Version 83.0.4103.97 (Official Build) (64-bit)

**Comment by retorquere** [comment]
You can edit the wiki to amend this - I don't own a chromebook so that page just has whatever experience others have with the debs. I use them for Linux myself.

**Comment by MaxGhenis** [comment]
Sure, edited. Thanks.
