### ISSUE TITLE
libnss3-dev depedency

### ISSUE THREAD

**Issue by mfonville** [retorquere/zotero-deb#30]
Hi,

I wondered why `libnss3-dev` is specified as dependency for Zotero.
I don't see it described as requirement for the official downloadable Zotero, neither wouldn't it be logically to have it as a dependency when installing. Isn't maybe just a `build-depends` for your release script?

**Comment by retorquere** [comment]
It's deliberate. I have no idea why Zotero (sometimes?) needs libnss3-dev, but there seems to be problem afflicting [multiple Debian-based systems](https://forums.zotero.org/search/?Search=libnss3-dev) that goes away if it is installed.

Are you experiencing problems because it gets dragged in?

**Comment by mfonville** [comment]
I don't have any problems, so it was just a question. It seemed so weird to have a development-headers dependency for executing the application. Thank you for your link to the forums, seems to be a bit strange behavior then from Zotero itself. Thank you for the information.

**Comment by retorquere** [comment]
I fully agree, and I can't think of a single reason why this should work. But apparently it does.

TBH I haven't tested whether the dependencies of `libnss3-dev` are what helps. `libnss3-dev` pulls in `libnss3`, maybe that's what is actually needed.
