### ISSUE TITLE
Error: Access was denied while trying to open files in your profile directory.

### ISSUE THREAD

**Issue by studiosusmed** [retorquere/zotero-deb#31]
Can someone help? I can't open zotero. It shows the following error: 
`Access was denied while trying to open files in your profile directory.`

I don't know what to do. Flatpak zotero is installed and works and can access my zotero folder. Thanks for your help in advance!
```
which zotero 
/usr/local/bin/zotero
```
```
uname -a
Linux XXX 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by retorquere** [comment]
Are you running the flatpack simultaneously?

**Comment by retorquere** [comment]
And who owns/what are the permissions on `~/Zotero`?

**Comment by studiosusmed** [comment]
no the flatpak app is closed, when i try to open deb zotero. 
I don't have a folder `~/Zotero` as I use for ages now `~/zotero.standalone` 
However I created the folder anyway but the error persists.

Thx for your help!

**Comment by retorquere** [comment]
How did you get zotero to look there rather than in the default place? Have you checked the rights of the files in that profile you use?

**Comment by studiosusmed** [comment]
For the flatpak / snap installation it would be rather easier: The first time zotero starts, it's just empty, then I'd be able to set the path to my library folder via the preferences. 

The directory and files are owned by my profile.

**Comment by retorquere** [comment]
Can you start Zotero using

```
zotero -ZoteroDebugText > ~/zotero.log
```

and see if there's more detail about what file it is not allowed to open?

There's just me BTW, so if there's someone, that would be me.

This install does work -- I run at least one test a day with it for another project, so I don't yet know what the cause could be.

**Comment by studiosusmed** [comment]
bug hunting  ain't fun, when the log stays empty! Sorry retorquere no entry in the log file.
i know that your deb is just fine. it's my end that is producing horsesh**.

**Comment by retorquere** [comment]
> For the flatpak / snap installation it would be rather easier: The first time zotero starts, it's just empty, then I'd be able to set the path to my library folder via the preferences.

Which preferences are those? I don't see anything that sounds like "set profile dir" in the Zotero preferences.

Can you try starting Zotero with `zotero -P`? It should pop up the profile picker; create a new profile and see if that worls as expected.

**Comment by studiosusmed** [comment]
> Which preferences are those? I don't see anything that sounds like "set profile dir" in the Zotero preferences.

In the advanced tab, in the files and folder section, there you're able to change the Data directory location. see the attached screenshot.
![image](https://user-images.githubusercontent.com/7684511/97775553-e6081880-1b61-11eb-825b-f2809d207f81.png)

`zotero -P` produces the same error.

**Comment by retorquere** [comment]
That's the data directory, not the profile directory. On linux, the default profile directory is `~/.zotero/zotero`.

**Comment by studiosusmed** [comment]
jep, my bad. sorry! so i'd just change the data directory.
`~/.zotero/zotero` is fully accessible btw.

**Comment by retorquere** [comment]
But also the profile below it, and all files in it? Because zotero is complaining about one of the files there.

Can you download the Zotero tarball, unpack it, and just start that Zotero with `./zotero`? I think it will exhibit the same behavior, and if that's the case, the zotero devs would likely be able to tell what's going on better than me.

**Comment by studiosusmed** [comment]
Yes, indeed same behaviour. thx. I'll take it to the zotero devs, hope that they have another hint! thx so much!

**Comment by studiosusmed** [comment]
The trick was to delete ~/.cache/zotero
`rm -r ~/.cache/zotero`
