### ISSUE TITLE
Debian install script apt-key command depreciated

### ISSUE THREAD

**Issue by weleoka** [retorquere/zotero-deb#32]
When running `https://github.com/retorquere/zotero-deb/releases/download/apt-get/install.sh` there is a warning raised that the apt-key command is depreciated. 

To reproduce, and the resulting warning: 
```
wget -qO- https://github.com/retorquere/zotero-deb/releases/download/apt-get/install.sh | sudo bash
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
```

The relevant lines in the script are: 

```
if [ -x "$(command -v curl)" ]; then
  curl --silent -L https://github.com/retorquere/zotero-deb/releases/download/apt-get/deb.gpg.key | sudo apt-key add -
elif [ -x "$(command -v wget)" ]; then
  wget -qO- https://github.com/retorquere/zotero-deb/releases/download/apt-get/deb.gpg.key | sudo apt-key add -
else
  echo "Error: need wget or curl installed." >&2
  exit 1
fi
```

Reading the man pages `man apt-key 8` we see the message: `apt-key(8) will last be available in Debian 11 and Ubuntu 22.04`.

Other software has similar issues of course, here is an Ansible [issue report](https://github.com/ansible/ansible/issues/55590).

A solution could be to run curl or wget and write to the `/etc/apt/trusted.gpg.d` directory... however, it needs to be in a "keyring" file 
(just putting a key in `/etc/apt/trusted.gpg.d` does not work: `curl --silent -L https://github.com/retorquere/zotero-deb/releases/download/apt-get/deb.gpg.key -o /etc/apt/trusted.gpg.d/zotero-deb.gpg.key` fails). So the script would have to create a keyring, and then add the Zotero gpg key to that keyring, and then place the keyring in the said directory.

**apt** has a keyring called `/etc/apt/trusted.gpg`where `apt-key add`puts its keys. So the "new" command could be something like:

```
$ curl --silent -L https://github.com/retorquere/zotero-deb/releases/download/apt-get/deb.gpg.key | gpg --no-default-keyring --keyring /etc/apt/trusted.gpg --import -

gpg: key EB9B577A1C349BFC: public key "dpkg <dpkg@iris-advies.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

**Comment by retorquere** [comment]
Thanks for the fix!

**Comment by weleoka** [comment]
Seems like there's a bit of a can of worms going on in the other issue #33 ... sorry about that... hope it's not to entierly to do with this post I submitted.

I see you changed the install script to have the line in the script to:
`curl --silent -L $url/deb.gpg.key | gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/zotero.gpg --import -` ... I must ask what the `gnupg-ring:` bit is about? Also, anything I can do to help in the other issue?

**Comment by retorquere** [comment]
I'm still trying to figure out what is going on. Some of it has to do with the gpg keys but that's worked since forever, and info on what has actually changed is scant. I'm also trying to recover some info from older builds, but Travis (where the info lives), which usually had super responsive support has just gone completely silent the past month.

**Comment by weleoka** [comment]
This [post here](https://askubuntu.com/a/1300076) has an idea on what replaces the legacy `apt-key` command.

**Comment by retorquere** [comment]
The install.sh [does exactly that](https://github.com/retorquere/zotero-deb/blob/master/install.sh#L23) -- the call to `apt-key` is an attempt to remove the deprecated key so that people don't get "deprecated key" warnings at every install. I'll remove the call to `apt-key` in a while after it's plausible most people have underwent this procedure.

Why Ubuntu et all don't just convert those deprecated keys is a mystery to me.

**Comment by weleoka** [comment]
As a follow-up, again for anyone interested, in the deb / apt / keyrings / signing ecosystem there's another great post at: [Ask Ubuntu](https://askubuntu.com/a/1307181)] about what replaces `apt-key`.

**Comment by retorquere** [comment]
That is very useful. I think I can incorporate that.

**Comment by xmaster2121** [comment]
Hello Friends, i have Ubuntu 21.04, i want  download katoolin3
When running 

sudo ./install.sh;
there is a warning raised that the apt-key command is depreciated.
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.LfGGzVtUjS/gpg.1.sh -qq --keyserver pool.sks-keyservers.net --recv-keys ED444FF07D8D0BF6
can anyone help me please

**Comment by retorquere** [comment]
That is a warning, not an error. Have you tried the rest of the commands?

**Comment by xmaster2121** [comment]
I tried the rest Commands but I still have Same problem, if you want I can send to you my ID Anydesk

**Comment by retorquere** [comment]
What is the output of those other commands?

**Comment by xmaster2121** [comment]
https://github.com/s-h-3-l-l/katoolin3

**Comment by xmaster2121** [comment]
git clone https://github.com/s-h-3-l-l/katoolin3;
cd katoolin3;
chmod +x ./install.sh;
sudo ./install.sh;

**Comment by xmaster2121** [comment]
Can you please access my device per Anydesk and you can see what I have problem

**Comment by xmaster2121** [comment]
![Uploading 1632601296444999110664574614824.jpg…]()

**Comment by retorquere** [comment]
> Hello Friends, i have Ubuntu 21.04, i want download katoolin3

You are on the wrong repo. Katoolin has nothing to do with my Zotero packages. Try asking at https://github.com/s-h-3-l-l/katoolin3/issues

> Can you please access my device per Anydesk and you can see what I have problem

No. I only do support using these boards, and in any case, I don't do support for random unrelated packages. Ask https://github.com/s-h-3-l-l/katoolin3/issues

**Comment by juliangilbey** [comment]
Unfortunately the new version doesn't work either:
```
gpg: keyblock resource '/etc/apt/trusted.gpg.d/zotero.gpg': No such file or directory
```
This gpg command can't actually create the keyring :-(

**Comment by retorquere** [comment]
When you say "the new version", what commands did you run?

**Comment by juliangilbey** [comment]
I effectively ran:
```sh
wget -qO- https://downloads.sourceforge.net/project/zotero-deb/install.sh | sudo bash
```

But I don't like running random scripts as root without looking at them first, so I actually did the following:
```sh
wget https://downloads.sourceforge.net/project/zotero-deb/install.sh
```
then looked at the script.  It turns out only a small amount of the script requires sudo privileges, and they are all explicitly marked with `sudo` in the script.  So I just ran `bash install.sh`.  But that didn't work because the script has a check that you're running as root.  So I removed that check and then the script failed for the reason I explained a couple of posts ago.  But modifying the script by adding the `--no-options` option to the `gpg` calls fixed it, and it allowed me to run `bash install.sh` with no further problems.

**Comment by retorquere** [comment]
Good on you for being cautious here, but I don't really know how this will affect install/update. If it works, good, and good point that the script doesn't actually need to run as root, I'll probably change the instructions and remove the check. If you encounter problems, please let me know, but I interpreted your description as "I followed the instructions and got an error", and that's not the case. Nothing wrong whatsoever with your approach, and more people should do this, but I needed this information to be able to assess what problems you were experiencing.

**Comment by juliangilbey** [comment]
The problem is not in the way I called the script; I tried the officially advertised way later and it also failed.  The problem is with the `gpg` call.  The fix is to add the `--no-option` option to the `gpg` calls.

**Comment by retorquere** [comment]
What platform are you on? I test the deployment at least once a day in my test suite, and that runs without issue.

**Comment by retorquere** [comment]
In any case `--no-options` should do no harm, so I'll just add that.

**Comment by retorquere** [comment]
> Unfortunately the new version doesn't work either:
> 
> ```
> gpg: keyblock resource '/etc/apt/trusted.gpg.d/zotero.gpg': No such file or directory
> ```

This will be because you ran the script as another user than root. If I remove the requirement to run as `sudo bash`, the gpg line must be

```
curl --silent -L $GPGKEY | sudo gpg --no-default-keyring --keyring $KEYRING --import -
```

because a non-wheel user cannot create this keyring.

**Comment by retorquere** [comment]
A complete sudo-ified script would be

```
case `uname -m` in
  "i386" | "i686" | "x86_64")
    ;;
  *)
    echo "Zotero is only available for architectures i686 and x86_64"
    exit
    ;;
esac

BASEURL=https://github.com/retorquere/zotero-deb/releases/download/apt-get
CODENAME=.
GPGKEY=$BASEURL/$CODENAME/deb.gpg.key
KEYRING=gnupg-ring:/etc/apt/trusted.gpg.d/zotero.gpg
if [ -x "$(command -v curl)" ]; then
  curl --silent -L $GPGKEY | sudo gpg --no-default-keyring --keyring $KEYRING --import -
elif [ -x "$(command -v wget)" ]; then
  wget -qO- $GPGKEY | sudo gpg --no-default-keyring --keyring $KEYRING --import -
else
  echo "Error: need wget or curl installed." >&2
  exit 1
fi

sudo chmod 644 /etc/apt/trusted.gpg.d/zotero.gpg

cat << EOF | sudo tee /etc/apt/sources.list.d/zotero.list
deb [by-hash=force] $BASEURL $CODENAME/
EOF

sudo apt-get clean
```

**Comment by retorquere** [comment]
The key location has changed to fix these issues; the existing setup will work without change, but re-running `install.sh` (or inspecting it and running the steps by hand, natch) will bring the location of the key file and related registration up to date.
