### ISSUE TITLE
Name=Juris-M in zotero.desktop for Zotero install

### ISSUE THREAD

**Issue by sjkillen** [retorquere/zotero-deb#36]
Not sure if this is the right place to report this issue, but it seems I have installed Zotero from here. Recently the Name entry in /usr/share/applications/zotero.desktop changed from Zotero to Juris-M.
When I check help>>about in Zotero it says that I have Zotero installed.

**Comment by retorquere** [comment]
This is the right place -- thanks for reporting this, a fix is building.

**Comment by retorquere** [comment]
The repo is updated with a fix -- an `update`/`upgrade` should get you 5.0.93-1 which should be correctly labeled.

**Comment by retorquere** [comment]
Does this mean it's indeed fixed for you?

**Comment by sjkillen** [comment]
Yes, the name is Zotero now after an apt update/upgrade. Thanks!
