### ISSUE TITLE
Failed Checksum

### ISSUE THREAD

**Issue by The-Pezman** [retorquere/zotero-deb#37]
I tried installing Zotero, and this time it started to work! But then I got this issue:

![image](https://user-images.githubusercontent.com/6238366/100956436-71205980-34e6-11eb-9b94-8bb056b80e71.png)

Looks like a file is corrupt or not being verified correctly.

**Comment by retorquere** [comment]
Just guessing, but maybe I was just updating the repo and something was mid-upload? Can you try again?

**Comment by The-Pezman** [comment]
I had to redo the wget, but this time it worked!

**Comment by retorquere** [comment]
That's not so great -- that means more people will have to do this. I'm trying to figure out why this should be the case.

**Comment by retorquere** [comment]
Oh wait -- phew, it's just a file size mismatch. I might have been updating the repo at the time. I thought it was a key mismatch.

**Comment by retorquere** [comment]
The wget really shouldn't have helped for this -- the checksum wasn't off, it was the filesize. I did find a problem with the file sizes, that should now be fixed.
