### ISSUE TITLE
Problem with public key

### ISSUE THREAD

**Issue by Jakethethird** [retorquere/zotero-deb#38]
Hello,
I have an issue with updating and your public key on Ubuntu 20.10

(Thank you for your great work!)

during apt update: 

Err:8 https://github.com/retorquere/zotero-deb/releases/download/apt-get ./ InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 996BEED4A27FACBD

W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://github.com/retorquere/zotero-deb/releases/download/apt-get ./ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 996BEED4A27FACBD
W: Failed to fetch https://github.com/retorquere/zotero-deb/releases/download/apt-get/./InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 996BEED4A27FACBD

jake@jake:~$ sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 996BEED4A27FACBD
Executing: /tmp/apt-key-gpghome.POBXiQ8cAo/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 996BEED4A27FACBD
gpg: keyserver receive failed: No data

**Comment by retorquere** [comment]
What does `apt-key list` say?

**Comment by moemode** [comment]
I face the same issue. In my case `apt-key list | grep iris-advies` says:
```
apt-key list | grep iris-advies
Warning: apt-key output should not be parsed (stdout is not a terminal)
uid           [ unknown] dpkg <dpkg@iris-advies.com>
```

**Comment by retorquere** [comment]
and just `apt-key list` shows (a.o.) this?

```
/etc/apt/trusted.gpg.d/zotero.gpg
---------------------------------
pub   rsa4096 2018-10-20 [SC]
      6B08 A882 2B39 5BCA 067C  88AA EB9B 577A 1C34 9BFC
uid           [ unknown] dpkg <dpkg@iris-advies.com>
```

**Comment by retorquere** [comment]
I've just installed this repo on a fresh install of Ubuntu 20.10, and I can't replicate the problem yet.

**Comment by Retrotux** [comment]
I'm experiencing the same issue (elementaryOS 5, based on Ubuntu 18.04).

**Comment by moemode** [comment]
Yes it shows that. `apt-key list`
```
/etc/apt/trusted.gpg
--------------------
pub   rsa4096 2018-10-20 [SC]
      6B08 A882 2B39 5BCA 067C  88AA EB9B 577A 1C34 9BFC
uid           [ unknown] dpkg <dpkg@iris-advies.com>
```
To give more context: I installed a while ago on ubuntu 20.04. Until recently no problems with apt update. Its quite likely the problem was introduced in the last couple days from my perspective.

**Comment by moemode** [comment]
Shouldn't the key in trusted.gpg and the one apt is complaining about agree?

**Comment by retorquere** [comment]
What does `file /etc.apt/trusted.gpg` say?

The key location and format that apt accepts seems to have changed in a recent version -- I did install it in `/etc/apt/trusted.gpg` for a long time, and that resulted in keys in the `GPG keybox database` format, but for whatever reason, it must now be in its own file (I chose `/etc/apt/trusted.gpg.d/zotero.gpg`) and must be in the `PGP/GPG key public ring (v4)` format. The install.sh script will add the new key but does not currently remove the old key.

Can you try `sudo apt-key --keyring /etc/apt/trusted.gpg del 1C349BCF`, and then re-run the `install.sh`?

**Comment by moemode** [comment]
Thanks for your help. The issue was indeed resolved by this two command sequence:
`sudo apt-key --keyring /etc/apt/trusted.gpg del 1C349BCF`
`wget -qO- https://github.com/retorquere/zotero-deb/releases/download/apt-get/install.sh | sudo bash`

**Comment by retorquere** [comment]
Cool, then I'm adding that to the `install.sh`

**Comment by scanno** [comment]
Saves the problem on my side also

**Comment by Retrotux** [comment]
Reinstalled the deb-package with the new command, problem solved :+1:

**Comment by Jakethethird** [comment]
I opened this issue this morning. The command below solved the issue for me.
```
sudo apt-key --keyring /etc/apt/trusted.gpg del 1C349BCF
wget -qO- https://github.com/retorquere/zotero-deb/releases/download/apt-get/install.sh | sudo bash
```
Thanks!

**Comment by retorquere** [comment]
The new `install.sh` performs the old key removal automatically. Don't know why Ubuntu doesn't just migrate these keys -- they're public keys so they should be extractable.
