### ISSUE TITLE
Wrong name in zotero.desktop

### ISSUE THREAD

**Issue by jmpowers** [retorquere/zotero-deb#41]
The Name field in /usr/share/applications/zotero.desktop is "Juris-M" when it should be "Zotero".

**Comment by retorquere** [comment]
And you're on `5.0.93-2`?

**Comment by retorquere** [comment]
Because this issue did exist but was fixed in #36

**Comment by jmpowers** [comment]
Yes - fixed by updating to 5.0.93-2. Should have checked the closed issues. Thanks!

**Comment by retorquere** [comment]
But weren't you upgraded automatically?
