### ISSUE TITLE
Problem upgrading to 5.0.96.2 (fixed)

### ISSUE THREAD

**Issue by Chrunchbang** [retorquere/zotero-deb#43]
Hi, I am on Debian Buster 10 with kde, I have installed Zotero package from https://github.com/retorquere/zotero-deb/releases/download/apt-get/  repository with `# apt install zotero`
Today `apt update` tell me that there is an update for Zotero, but if I give an `# apt upgrade` nothing is upgraded. Giving an `apt upgrade zotero` the command tell me that there is an insatisfied dependency libgcc-s1 that there is not installable.
Indeed libgcc-s1 is available only on Debian Bullseye 11 and in Debian Sid.
What can i do? Thank you for help

**Comment by retorquere** [comment]
What does `apt-cache depends firefox-esr` say on your system?

**Comment by Chrunchbang** [comment]
`$ apt-cache depends firefox-esr
firefox-esr
  Dipende: libatk1.0-0
  Dipende: libc6
  Dipende: libcairo-gobject2
  Dipende: libcairo2
  Dipende: libdbus-1-3
  Dipende: libdbus-glib-1-2
  Dipende: libevent-2.1-6
  Dipende: libffi6
  Dipende: libfontconfig1
  Dipende: libfreetype6
  Dipende: libgcc1
  Dipende: libgdk-pixbuf2.0-0
  Dipende: libglib2.0-0
  Dipende: libgtk-3-0
  Dipende: libpango-1.0-0
  Dipende: libstdc++6
  Dipende: libx11-6
  Dipende: libx11-xcb1
  Dipende: libxcb-shm0
  Dipende: libxcb1
  Dipende: libxcomposite1
  Dipende: libxdamage1
  Dipende: libxext6
  Dipende: libxfixes3
  Dipende: libxrender1
  Dipende: zlib1g
  Dipende: fontconfig
  Dipende: procps
  Dipende: debianutils
  Va in conflitto: iceweasel
  Rompe: <xul-ext-torbutton>
 |Raccomanda: libavcodec58
    libavcodec-extra58
 |Raccomanda: libavcodec-extra58
 |Raccomanda: <libavcodec57>
 |Raccomanda: <libavcodec-extra57>
 |Raccomanda: <libavcodec56>
 |Raccomanda: <libavcodec-extra56>
 |Raccomanda: <libavcodec55>
 |Raccomanda: <libavcodec-extra55>
 |Raccomanda: <libavcodec54>
 |Raccomanda: <libavcodec-extra54>
 |Raccomanda: <libavcodec53>
  Raccomanda: <libavcodec-extra53>
 |Consiglia: fonts-stix
  Consiglia: <otf-stix>
    fonts-stix
  Consiglia: fonts-lmodern
 |Consiglia: libgssapi-krb5-2
  Consiglia: <libkrb53>
  Consiglia: libcanberra0
  Consiglia: libgtk2.0-0
  Consiglia: pulseaudio`

I believe that on Debian Buster 10 there is libgcc1 instead of libgcc-s1

**Comment by retorquere** [comment]
Can you try update/upgrade again?

**Comment by Chrunchbang** [comment]
It works, thank you very much! Thank you also for your Zotero repository on Debian, it's very useful

**Comment by retorquere** [comment]
You're welcome.
