### ISSUE TITLE
Mint Ulyana: Dependencies are not correctly resolved

### ISSUE THREAD

**Issue by sebadrude** [retorquere/zotero-deb#44]
Hi, thanks for this work!
I am not able to install Zotero on my Linux Mint Ulyana system, though.

Here the output:

$ sudo apt install zotero
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 gstreamer1.0-plugins-bad : Depends: libgstreamer-plugins-bad1.0-0 (= 1.18.4-3) but 1.16.2-2.1ubuntu1 is to be installed
 gstreamer1.0-vaapi : Depends: libgstreamer-plugins-bad1.0-0 (>= 1.18.3) but 1.16.2-2.1ubuntu1 is to be installed
 zotero : Depends: libnss3-dev but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

I tried 'apt --fix-broken install', but I get the help pages for apt.

I do not want to install Zotero from Mint's software manager because the installation seems to have problems (not opending attached PDFs etc.).

Any advice?

**Comment by retorquere** [comment]
Can you try update/upgrade again?

**Comment by sebadrude** [comment]
Thanks for coming back to this so quickly.
Yes, I just have tried the same command, `sudo apt install zotero` (although in the meanwhile I have installed Zotero from the tar-ball that is offered on the Zotero download pages).  I am sorry, the result seems to be the same:
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 gstreamer1.0-plugins-bad : Depends: libgstreamer-plugins-bad1.0-0 (= 1.18.4-3) but 1.16.2-2.1ubuntu1 is to be installed
 gstreamer1.0-vaapi : Depends: libgstreamer-plugins-bad1.0-0 (>= 1.18.3) but 1.16.2-2.1ubuntu1 is to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
`

**Comment by retorquere** [comment]
You must first do `apt update` because it will still be trying to install `5.0.96.2-1` which you fetched info on before. Your system won't know that `5.0.96.2-2` is available until you `apt update`.

**Comment by retorquere** [comment]
Can you try removing and re-installing? `apt` may still be trying to fix-install `5.0.96.2-1`.

**Comment by sebadrude** [comment]
Hi Emiliano,

sorry if I am slow here, but how do you mean -- I should unsinstall the 
installed Zotero?  Or what should I "remove"?

Sebastian

**Comment by sebadrude** [comment]
I have version 5.0.96.2 installed from Zotero-5.0.96.2_linux-x86_64.tar.bz2

URL: 
https://www.zotero.org/download/client/dl?channel=release&platform=linux-x86_64&version=5.0.96.2

Sebastian

-- 
Museu P.E. Goeldi, CCH, Linguistica ▪ Av. Perimetral, 1901
Terra Firme, CEP: 66077-530 ▪ Belém do Pará – PA ▪ Brazil
***@***.*** ▪ +55 (91) 3217 6024 ▪ +55 (91) 983733319
Priv: Tv. Juvenal Cordeiro, 184, Apt 104 ▪ 66070-300 Belém

**Comment by retorquere** [comment]
> Hi Emiliano, sorry if I am slow here, but how do you mean -- I should unsinstall the installed Zotero?  Or what should I "remove"? Sebastian

Nothing, I misread your reply.

> I have version 5.0.96.2 installed from Zotero-5.0.96.2_linux-x86_64.tar.bz2 URL: https://www.zotero.org/download/client/dl?channel=release&platform=linux-x86_64&version=5.0.96.2 

That's the official tarball, that is not related to the `.deb` install other that they end up putting the same binaries on your system.

What does `dpkg -l | grep zotero` say?

**Comment by sebadrude** [comment]
Right. Sorry if I was not clear enough.

|dpkg -l | grep zotero|

does not give me anything, I am afraid, no error message, no output either.

Same with |sudo dpkg -l | grep zotero|



Sebastian

-- 
Museu P.E. Goeldi, CCH, Linguistica ▪ Av. Perimetral, 1901
Terra Firme, CEP: 66077-530 ▪ Belém do Pará – PA ▪ Brazil
***@***.*** ▪ +55 (91) 3217 6024 ▪ +55 (91) 983733319
Priv: Tv. Juvenal Cordeiro, 184, Apt 104 ▪ 66070-300 Belém

**Comment by retorquere** [comment]
And what is the output of

```
apt remove gstreamer1.0-plugins-bad gstreamer1.0-vaapi
apt update
apt install zotero
```

**Comment by sebadrude** [comment]
***@***.****:*~*$ apt remove gstreamer1.0-plugins-bad gstreamer1.0-vaapi
[sudo] password for sebastian:
Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
  libcheese8 : Depends: gstreamer1.0-plugins-bad (>= 1.4) but it is not going to be installed
  libges-1.0-0 : Depends: gstreamer1.0-plugins-bad (>= 1.18.0) but it is not going to be installed
  mint-meta-codecs : Depends: gstreamer1.0-plugins-bad but it is not going to be installed
                     Depends: gstreamer1.0-vaapi but it is not going to be installed
*E: *Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
***@***.****:*~*$ apt update
Ign:1 http://mirror.ufscar.br/mint-archive ulyana InRelease
Hit:2 http://mirror.ufam.edu.br/ubuntu focal InRelease
Hit:3 http://mirror.ufscar.br/mint-archive ulyana Release
Get:4 http://mirror.ufam.edu.br/ubuntu focal-updates InRelease [114 kB]
Hit:5 http://ftp.br.debian.org/debian bullseye InRelease
Hit:6 http://dl.google.com/linux/chrome/deb stable InRelease
Get:8 http://mirror.ufam.edu.br/ubuntu focal-backports InRelease [101 kB]
Hit:9 https://repo.skype.com/deb stable InRelease
Hit:10 http://ppa.launchpad.net/obsproject/obs-studio/ubuntu focal InRelease
Get:11 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Hit:13 http://repository.spotify.com stable InRelease
Get:14 http://mirror.ufam.edu.br/ubuntu focal-updates/main amd64 DEP-11 Metadata [283 kB]
Hit:15 http://archive.canonical.com/ubuntu focal InRelease
Get:16 http://mirror.ufam.edu.br/ubuntu focal-updates/universe amd64 DEP-11 Metadata [339 kB]
Get:17 http://mirror.ufam.edu.br/ubuntu focal-updates/multiverse amd64 DEP-11 Metadata [2.468 B]
Get:18 http://mirror.ufam.edu.br/ubuntu focal-backports/universe amd64 DEP-11 Metadata [10,3 kB]
Hit:12 https://github.com/retorquere/zotero-deb/releases/download/apt-get ./ InRelease
Get:19 http://security.ubuntu.com/ubuntu focal-security/main amd64 DEP-11 Metadata [27,6 kB]
Get:20 http://security.ubuntu.com/ubuntu focal-security/universe amd64 DEP-11 Metadata [60,9 kB]
Get:21 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 DEP-11 Metadata [2.464 B]
Fetched 1.054 kB in 2s (561 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
2118 packages can be upgraded. Run 'apt list --upgradable' to see them.
***@***.****:*~*$ apt install zotero
Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
  gstreamer1.0-plugins-bad : Depends: libgstreamer-plugins-bad1.0-0 (= 1.18.4-3) but 1.16.2-2.1ubuntu1 is to be installed
  gstreamer1.0-vaapi : Depends: libgstreamer-plugins-bad1.0-0 (>= 1.18.3) but 1.16.2-2.1ubuntu1 is to be installed
*E: *Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
***@***.****:*~*$

  

Sebastian

-- 
Museu P.E. Goeldi, CCH, Linguistica ▪ Av. Perimetral, 1901
Terra Firme, CEP: 66077-530 ▪ Belém do Pará – PA ▪ Brazil
***@***.*** ▪ +55 (91) 3217 6024 ▪ +55 (91) 983733319
Priv: Tv. Juvenal Cordeiro, 184, Apt 104 ▪ 66070-300 Belém

**Comment by retorquere** [comment]
You must resolve the broken-package state on your system before we can do anything unfortunately. At this point it's not related to the zotero install.

> 2118 packages can be upgraded. Run 'apt list --upgradable' to see them

your system may have been in this state for a while.

**Comment by sebadrude** [comment]
I see.  I relied on the Mint Update Manager to do the upgrades.

If I just try apt upgrade, I get the same error message indeed.  So 
probably I will have to uninstall the package where 1.16.2-2.1ubuntu1 
comes from, right?

I will figure out how to do that and if the problem persists, I will 
come back to you via this email thread, is that okay?

Sebastian

-- 
Museu P.E. Goeldi, CCH, Linguistica ▪ Av. Perimetral, 1901
Terra Firme, CEP: 66077-530 ▪ Belém do Pará – PA ▪ Brazil
***@***.*** ▪ +55 (91) 3217 6024 ▪ +55 (91) 983733319
Priv: Tv. Juvenal Cordeiro, 184, Apt 104 ▪ 66070-300 Belém

**Comment by retorquere** [comment]
Absolutely. I wish I could be of more help, but the broken-package state is... not fun. I usually ended up uninstalling heaps of packages and retrying fix-install between. Not a great process.

**Comment by sebadrude** [comment]
Thanks, you have been very helpful already.

I am sorry to have bothered you woth something unrelated to your Zotero 
packaging, but to my insufficient Linux/Ubuntu/Mint package management 
knowledge, as it turned out.

It seems synaptics will identify the broken packages.  let's see.

Thanks again,

Sebastian

-- 
Museu P.E. Goeldi, CCH, Linguistica ▪ Av. Perimetral, 1901
Terra Firme, CEP: 66077-530 ▪ Belém do Pará – PA ▪ Brazil
***@***.*** ▪ +55 (91) 3217 6024 ▪ +55 (91) 983733319
Priv: Tv. Juvenal Cordeiro, 184, Apt 104 ▪ 66070-300 Belém

**Comment by retorquere** [comment]
The first error wrt nss3-dev was really related to my packaging, the -2 version removed that dependency. So it wasn't for nothing, but that error is now gone, and apparently apt won't let us proceed until the other errors are also gone.

**Comment by sebadrude** [comment]
Ah, fine, good to know.

So I'll keep you posted.

Currently waiting for all the updates to be applied...

Sebastian

-- 
Museu P.E. Goeldi, CCH, Linguistica ▪ Av. Perimetral, 1901
Terra Firme, CEP: 66077-530 ▪ Belém do Pará – PA ▪ Brazil
***@***.*** ▪ +55 (91) 3217 6024 ▪ +55 (91) 983733319
Priv: Tv. Juvenal Cordeiro, 184, Apt 104 ▪ 66070-300 Belém

**Comment by sebadrude** [comment]
wow, 39 partly boken packages, mostly with broken dependencies, one 
package completely broken if I understand that right.

Pressing the "fix broken packages" button in Synaptics will not do the 
trick.

I will have to research about how to tackle these issues, but as you 
wrote that might be quite a nuisance.

Will continue to do so in the coming days, now it's getting late here.

Sebastian

-- 
Museu P.E. Goeldi, CCH, Linguistica ▪ Av. Perimetral, 1901
Terra Firme, CEP: 66077-530 ▪ Belém do Pará – PA ▪ Brazil
***@***.*** ▪ +55 (91) 3217 6024 ▪ +55 (91) 983733319
Priv: Tv. Juvenal Cordeiro, 184, Apt 104 ▪ 66070-300 Belém

**Comment by retorquere** [comment]
Fix install only occasionally fixed the matter for me. Don't worry about keeping me in the loop, I'll help where I can.

**Comment by retorquere** [comment]
Any progress?

**Comment by sebadrude** [comment]
Thanks for asking, Emiliano!

I was offline over the weekend, as always, on an island in the nature, 
detoxing from too much screen-time during the week...

I almost destroyed my system last week when I deleted some broken 
packages and tried to get rid of numerous other reported problems -- but 
I did that without really understanding how the dependencies work etc.  
So, next time I wanted to boot, the system does not even give me a 
login-page.

Thanks heavens I had timeshift activated and so I managed, with a 
bootable system on USB-stick, to revert the situation to before -- still 
with the broken packages.

On tuesday a friend of mine promised to visit me in the afternoon and 
help me to solve the broken-package problem without damaging my system, 
I hope ;-)

I will report on late Tuesday (I am in Brazil).

Thanks again, you are being very helpful and friendly!

Sebastian

-- 
Museu P.E. Goeldi, CCH, Linguistica ▪ Av. Perimetral, 1901
Terra Firme, CEP: 66077-530 ▪ Belém do Pará – PA ▪ Brazil
***@***.*** ▪ +55 (91) 3217 6024 ▪ +55 (91) 983733319
Priv: Tv. Juvenal Cordeiro, 184, Apt 104 ▪ 66070-300 Belém

**Comment by retorquere** [comment]
> I was offline over the weekend, as always, on an island in the nature, 
> detoxing from too much screen-time during the week... 

That sounds nice
> 
> I almost destroyed my system last week when I deleted some broken 
> packages and tried to get rid of numerous other reported problems -- but 
> I did that without really understanding how the dependencies work etc.  
> So, next time I wanted to boot, the system does not even give me a 
> login-page.

Ouch. 

> I will report on late Tuesday (I am in Brazil).

That's fine, no rush
