### ISSUE TITLE
Release file problem again

### ISSUE THREAD

**Issue by silpol** [retorquere/zotero-deb#45]
I have Ubuntu system with 

> $ lsb_release -rd
Description:	Ubuntu 20.04.2 LTS
Release:	20.04

after next update drill, I got message

> $ sudo apt update
...
Err:28 https://github.com/retorquere/zotero-deb/releases/download/apt-get ./ Release                                                      
  404  Not Found [IP: 185.199.110.154 443]
Reading package lists... Done                                            
E: The repository 'https://github.com/retorquere/zotero-deb/releases/download/apt-get ./ Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

it looks like regression - this might be old issue #23 had hit again?

**Comment by retorquere** [comment]
Not sure what the problem could be, as I could download the Release file just now without problem, and the daily tests ran on github perform this procudure without errors. If you just try to download that file with a browser, what do you get?

**Comment by silpol** [comment]
Yeha, problems has gone since then. Closed.

**Comment by jp-um** [comment]
I think I have to reopen this (sorry!).  As of today!

```
$ sudo apt update
[...snip...]
Ign:20 https://github.com/retorquere/zotero-deb/releases/download/apt-get ./ InRelease
Err:21 https://github.com/retorquere/zotero-deb/releases/download/apt-get ./ Release
  404  Not Found [IP: 140.82.121.3 443]
Reading package lists... Done
E: The repository 'https://github.com/retorquere/zotero-deb/releases/download/apt-get ./ Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
Kindly note that this file `https://github.com/retorquere/zotero-deb/releases/download/apt-get ./ Release` returns a 404.

**Comment by retorquere** [comment]
Known problem. Please join issue #52.
