### ISSUE TITLE
How to run zotero bulit from its git master source code?

### ISSUE THREAD

**Issue by hongyi-zhao** [retorquere/zotero-deb#46]
I'm On Ubuntu 20.04.2 LTS, and try to build [`zotero`](https://github.com/zotero/zotero) from its git master source code, as shown below:

```
$ curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
$ sudo apt-get install -y nodejs
$ node --version
v16.8.0

$ git clone https://github.com/zotero/zotero.git zotero/zotero.git
$ cd zotero/zotero.git
$ git submodule update --recursive --init
$ proxychains-ng-http npm install
$ proxychains-ng-http npm run build
$ ls
build            components       defaults      note-editor        pdf-reader  resource  styles  translators
chrome           CONTRIBUTING.md  install.rdf   package.json       pdf-worker  scripts   test    update.rdf
chrome.manifest  COPYING          node_modules  package-lock.json  README.md   scss      tmp
```
I can't find any binary file named as `zotero`, so how to run `zotero` for this case?

Regards,
HY

**Comment by retorquere** [comment]
I have no idea - this repo purposefully just packages the binaries compiled bij the zotero project itself, I do not compile the binaries before packaging.

**Comment by hongyi-zhao** [comment]
See https://www.zotero.org/support/dev/client_coding/building_the_standalone_client for the detailed steps.

**Comment by retorquere** [comment]
Thanks, but as stated, I purposefully only package the binaries that Zotero have compiled themselves. I want to make sure that when a problem occurs, the Zotero people can trust it's with their own binaries, and not some flaw I compiled in.
