### ISSUE TITLE
Failed to fetch .deb Size mismatch

### ISSUE THREAD

**Issue by rebpan** [retorquere/zotero-deb#50]
```
E: Failed to fetch https://github.com/retorquere/zotero-deb/releases/download/apt-get/./jurism_5.0.93m18-2_amd64.deb  Size mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

encounter an error while installing jurism

**Comment by retorquere** [comment]
The repo might have been updating. Can you try again, and if that does not work, try the sourceforge mirror?

These problems are temporary, I'm moving the hosting to the zotero project itself.

**Comment by rebpan** [comment]
I'll try again later. Thank you very much!

**Comment by retorquere** [comment]
If it's a reload it should be done by now. Apologies for the disruption, I'm trying to find a permanent solution.

**Comment by rebpan** [comment]
Thank you very much for your contribution!
