### ISSUE TITLE
apt update throws out 404 error

### ISSUE THREAD

**Issue by errotu** [retorquere/zotero-deb#51]
First, thank you for your work! 

I'm using Zotero on Ubuntu and your service really makes my life easier. Unfortunately, I'm currently running into a 404 error whenever I'm updating my system (I translated the notifications to English):

> Err:11 https://github.com/retorquere/zotero-deb/releases/download/apt-get ./ Release
  404  Not Found [IP: 140.82.121.3 443]
> E: The repository ‘https://github.com/retorquere/zotero-deb/releases/download/apt-get ./ Release’ does not have a Release file.
> N: Updating from such a repository can’t be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

How can I fix this? Thank you in advance for your help!

**Comment by retorquere** [comment]
I'm working feverishly to get this fixed, but github has recently changed some things which triggered a bug in `apt`, and that broke everything. See #52.

**Comment by retorquere** [comment]
If you follow #52 you'll know when I have a solution, I'll post it there.

**Comment by errotu** [comment]
Thanks a lot for your great work!
