### ISSUE TITLE
PSA: github release downloads currently broken. Subscribe to this issue to keep up to date.

### ISSUE THREAD

**Issue by retorquere** [retorquere/zotero-deb#52]
I'm working feverishly to get the debs back up after an interaction between a change in how GH hosts its downloads and `apt` threw everything in disarray. I'm currently testing sourceforge hosting, paying for backblaze hosting, and working with Zotero to have them do the hosting (which would be the preferred and permanent option).

# Current status

* sourceforge downloads: tests green
  * install: `curl -sL https://downloads.sourceforge.net/project/zotero-deb/install.sh | sudo bash`
* github release downloads: tests green
  * requires patched apt: `sudo add-apt-repository ppa:tj/bugfixes && sudo apt-get update && sudo apt install apt`
  * install: `curl -sL https://downloads.sourceforge.net/project/zotero-deb/install.sh | sudo bash`
* b2 fallback: tests green
* hosting by Zotero: [under construction](https://github.com/zotero/zotero-standalone-build/issues/52)

Just in case you're wondering [what my weekend looked like](https://github.com/retorquere/zotero-deb/commits/master)...

**Comment by retorquere** [comment]
Fingers crossed, but tests have passed on the sourceforge-hosted packages. If you re-run the `install.sh` instructions from the [README](https://github.com/retorquere/zotero-deb) you should be up and running.

**Comment by jjstickel** [comment]
Thank you! For this fix and for making zotero available via an apt source.

**Comment by retorquere** [comment]
As of now, both the github hosting and the sourceforge hosting should work. If github hosting gives you *any* problems, please switch to sourceforge. I'm actively working with Zotero to get formal hosting by them set up, when that's done, I'll announce it here.

**Comment by RanjanPH** [comment]
Hello, I added the repo  https://github.com/retorquere/zotero-deb/releases/download/apt-get ./ InRelease and it's showing the errors (below mentioned) I want to remove the repo any idea how can I ??

Err:9 https://github.com/retorquere/zotero-deb/releases/download/apt-get ./ InRelease
  401  Unauthorized [IP: 185.199.111.133 443]
Reading package lists... Done
E: Failed to fetch https://github.com/retorquere/zotero-deb/releases/download/apt-get/./InRelease  401  Unauthorized [IP: 185.199.111.133 443]
E: The repository 'https://github.com/retorquere/zotero-deb/releases/download/apt-get ./ InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by retorquere** [comment]
It's in bottom of the [README](https://github.com/retorquere/zotero-deb).

If you just want to be rid of the error, not of  the repo, there are currently 2 options:

* install from my private hosting; the links in the README all point to that now. This should be stable.
* install from the official Zotero-provided deb hosting; that is expected to go live in the next two weeks

You can also do both; go to my private hosting now, move to the official hosting when it is live.

(un)installing is always the same process; run the `(un)install.sh` from the hosting you choose, that will remove the old repo from your system, and in the case if `install.sh`, switch to the new hosting. For `uninstall.sh`, it will only remove the repo. You can run the uninstall.sh from any hosting to fully remove the repo from your system.

**Comment by ace280** [comment]
Using the link provided in the [README section](https://github.com/retorquere/zotero-deb) '[Installing Zotero](https://github.com/retorquere/zotero-deb#installing-zotero)' works just fine.

Thank you for fixing and keeping us up to date ^^
