### ISSUE TITLE
Bug on debian updater

### ISSUE THREAD

**Issue by ppKrauss** [retorquere/zotero-deb#55]
After `sudo apt update`:

```
Reading package lists... Done
E: Failed to fetch https://github.com/retorquere/zotero-deb/releases/download/apt-get/./InRelease  401  Unauthorized [IP: 185.199.111.133 443]
E: The repository 'https://github.com/retorquere/zotero-deb/releases/download/apt-get ./ InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Please help to **purge** Zotero and its apt package

**Comment by retorquere** [comment]
I take it you have read the PSA [here](https://github.com/retorquere/zotero-deb)? https://github.com/retorquere/zotero-deb/releases/download/apt-get/./InRelease is downloadable, but github gives sporadic errors like these now, so I'm working with the Zotero project to have them do the hosting of these packages.

The packages are still signed, this is just one of the problems with the changes github made to their hosting. You can switch to the sourceforge mirror, which doesn't have this problem, or do the following to purge the apt packages:

```
sudo rm -f /usr/share/keyrings/zotero-archive-keyring.gpg
sudo rm -f /etc/apt/sources.list.d/zotero.list
sudo apt-get clean
sudo apt-get purge zotero
```

**Comment by ppKrauss** [comment]
Thanks @retorquere, now `sudo apt update`  is clean again! 

... I will try to install Zotero in 2020, but it needs a  **stable and secure installation**, with automatic updates (by `apt`) and  no PPA bugs.

**Comment by retorquere** [comment]
I have no control over when the apt bug is fixed, so I don't track that. When the hosting moves to Zotero the bug won't be triggered anymore.
