### ISSUE TITLE
Need for DNSSEC on installation server?

### ISSUE THREAD

**Issue by ppKrauss** [retorquere/zotero-deb#56]
As explained by Wikipedia and others, we need [DNS Security Extensions](https://en.wikipedia.org/wiki/Domain_Name_System_Security_Extensions) to avoid [DNS spoofing](https://en.wikipedia.org/wiki/DNS_spoofing) and similar problems.

The [installing instruction of Zotero-deb](https://github.com/retorquere/zotero-deb#installing-zotero--juris-m) say to use URLs with `sourceforge.net` domain, but, it is not authenticated.
 
**Test evidence**. For example `whois debian.org` shows `DNSSEC: signedDelegation`, so, it is authenticated. You can do the same test, `whois sourceforge.net`, and it  returns `DNSSEC: unsigned`.

**Comment by retorquere** [comment]
That will have to wait for the Zotero hosting, because I obviously don't control the sourceforge domain. Can you describe what they must do?

**Comment by ppKrauss** [comment]
> (...) Can you describe what they must do?

Sorry, I only know the Brazilian's tutorial, in Portuguese: https://registro.br/tecnologia/dnssec/dnssec-para-provedores/

**Comment by retorquere** [comment]
That looks like a generic description of how to set up dnssec, nothing specific to deb hosting. Zotero might have that set up for their domain already.

**Comment by mwt** [comment]
The repo is signed with a GPG key. This is what protects against DNS spoofing.

If you are particularly interested in DNSSEC, I happen to have a mirror that supports it:
https://mirror.mwt.me/zotero/deb/
