### ISSUE TITLE
B2 doesn't work

### ISSUE THREAD

**Issue by LucStk** [retorquere/zotero-deb#58]
I tried to install zotero from the B2 (wget -qO- https://apt.retorque.re/file/zotero-apt/install.sh | sudo bash).
I typed (apt update), then (apt install zotero) and I get the error (no package named zotero).
I was able to install the package from sourceforge though.

**Comment by retorquere** [comment]
It is back up now

**Comment by LucStk** [comment]
Nice, good job ! tx
