### ISSUE TITLE
desktop launcher missing capital first letters

### ISSUE THREAD

**Issue by alxsimon** [retorquere/zotero-deb#6]
First thank you for putting together this package.
I installed the global-menu version on Ubuntu 19.04 and couldn't find the launcher in the dash while the file `/usr/share/applications/zotero.desktop` existed.
I realised the first letters of each argument needed to be capitalized for it to work. After this modification it worked perfectly.

```
[Desktop Entry]
Name=Zotero
Comment=Open-source reference manager (global menu support)
Exec=/usr/lib/zotero/zotero --url %u
Icon=/usr/lib/zotero/chrome/icons/default/default48.png
Type=Application
Startupnotify=true
Mimetype=x-scheme-handler/zotero;ris;application/x-research-info-systems;application/x-endnote-refer;text/x-research-info-systems;text/application/x-research-info-systems;text/ris;ciw;isi;application/x-inst-for-Scientific-info;mods;application/mods+xml;rdf;application/rdf+xml;bib;bibtex;application/x-bibtex;text/x-bibtex;mrc;marc;application/marc;csl;vnd.citationstyles.style+xml
```

**Comment by retorquere** [comment]
Thanks for reporting this. I have fixed the problem, and the repo is rebuilding (should take about 10 minutes), at which stage you'll find a package with `-1` in the version number.

**Comment by retorquere** [comment]
That's `-2` because of #7, and it's up now.
