### ISSUE TITLE
None of the installations work

### ISSUE THREAD

**Issue by rongcuid** [retorquere/zotero-deb#61]
As title.

Also, the APT server doesn't seem to work either.:

```
W: Failed to fetch https://apt.retorque.re/file/zotero-apt/./InRelease  The HTTP server sent an invalid Content-Range header Bad header data [IP: 172.67.136.194 443]
```

**Comment by FilexD** [comment]
Same

**Comment by retorquere** [comment]
Working on it

**Comment by retorquere** [comment]
The installations work again, but see the [README](https://github.com/retorquere/zotero-deb). The new situation will be stable.

**Comment by jgieseler** [comment]
Hm, for me it still doesn't work:
``` bash
$ curl -sL https://zotero.retorque.re/file/apt-package-archive/install.sh | sudo bash
[sudo] password for xyz: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1150  100  1150    0     0   3125      0 --:--:-- --:--:-- --:--:--  3125
deb [signed-by=/usr/share/keyrings/zotero-archive-keyring.gpg by-hash=force] https://zotero.retorque.re/file/apt-package-archive ./

$ sudo apt update
Hit:1 http://fi.archive.ubuntu.com/ubuntu focal InRelease
[..]                            
Err:14 https://zotero.retorque.re/file/apt-package-archive ./ InRelease                     
  The HTTP server sent an invalid Content-Range header Bad header data [IP: 104.21.54.76 443]
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
W: Failed to fetch https://zotero.retorque.re/file/apt-package-archive/./InRelease  The HTTP server sent an invalid Content-Range header Bad header data [IP: 104.21.54.76 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by lyh458** [comment]
> 

same issue as you.

**Comment by lyh458** [comment]
Fixed, the github source work for me.
```
curl -sL https://github.com/retorquere/zotero-deb/releases/download/apt-get/install.sh | sudo bash
```

**Comment by retorquere** [comment]
On it, again. Cloudflare CDN seems to be the culprit. I'm working with two volunteers who have donated hosting, which means I can take cloudflare out of the mix if need be. The urls and install.sh stuff will remain the same though. That part at least is stable.

Never in a million years I would have thought the hosting part of this was going to be a painpoint. Yet here we are.

**Comment by retorquere** [comment]
I will keep the GH hosting updated, but my aim is to bring everyone to a single hosted place. This musical chairs between hosts is not a great user experience, and I don't want these problems to give anyone pause about my general competence.

**Comment by jgieseler** [comment]
Thanks a lot for your effort! 😊

But for me the github link also doesn't work; it complains that it's not signed. 😬

``` bash
$ curl -sL https://github.com/retorquere/zotero-deb/releases/download/apt-get/install.sh | sudo bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1150  100  1150    0     0  10360      0 --:--:-- --:--:-- --:--:-- 10454
deb [signed-by=/usr/share/keyrings/zotero-archive-keyring.gpg by-hash=force] https://github.com/retorquere/zotero-deb/releases/download/apt-get ./

$ sudo apt update
Err:11 https://github.com/retorquere/zotero-deb/releases/download/apt-get ./ InRelease
  401  Unauthorized [IP: 185.199.111.133 443]
Reading package lists... Done
E: Failed to fetch https://github.com/retorquere/zotero-deb/releases/download/apt-get/./InRelease  401  Unauthorized [IP: 185.199.111.133 443]
E: The repository 'https://github.com/retorquere/zotero-deb/releases/download/apt-get ./ InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by retorquere** [comment]
> But for me the github link also doesn't work; it complains that it's not signed. 😬

In my tests it does succeed: https://github.com/retorquere/zotero-deb/runs/5624606105?check_suite_focus=true

Maybe you found the repo mid-refresh (I'm doing a ton of them during the tests I'm doing right now). Can you retry? Or try the primary mirror?

**Comment by jgieseler** [comment]
The github mirror still gives the same error (not signed). But the primary mirror is working for me now! :partying_face:

**Comment by retorquere** [comment]
I intend to keep sourceforge and github updated, but I mean to move the supported option to https://zotero.retorque.re/apt-package-archive, wherever it ends up being hosted. Moving hosts, should it be necessary at some point, will be seamless for people using that repo.

**Comment by FilexD** [comment]
Here, everything seems working.

**Comment by Foggalong** [comment]
Everything working on my end now with Ubuntu 20.04.4 :slightly_smiling_face:

**Comment by retorquere** [comment]
It's been a ride.
