### ISSUE TITLE
set up mwt mirror

### ISSUE THREAD

**Issue by retorquere** [retorquere/zotero-deb#62]
@mwt I'd prefer it if we could continue here

**Comment by mwt** [comment]
That makes more sense. Just to check, this key you sent me:

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC/z3vcoTsQ1g9TAsDz7pBPLqJtJqcpfpCkk1XYAgEXR8Mkh3N9xbwIBLCDup9dOh40brBLPZgR8JsmuehOXHSx9XfuQlZKlK+Q6sOf9WEC6szrQTkI5puwSyjc/KCmbb/T8MaSUAmenS1ilTzphQvb0YqjyXakNVb4B2kv5iDiT9IzAiOwIAQZMKGoXtKKSqvRZPj6WsD4Cx47c4oQOFsiIStuSm0IGxxgvbaFqGf8hQAW4XYceskjs3Gpa2H7quYw4xUDsNQ3PUtw6Ab/FAcYQc/Im8pN77EIOROIKRYR59EYqVbgBJEHJP0tijbiZQTwF27wkfHx5R2GkHgNRk4zRhCt/eghDf7nLJg8fwn0bBBuX1orm+tUhGMYOu0rXcliXvmq5n7s6EaeShsQ+Z6pd0YbvfeQklLVmorQRQzr3a+Bbho9TEqQ8NlWgSqshSe8gxc47MGCnqLIvUnxjspvVuwxtq53K3aJXVQ+siXzFKFySjEvr04lbH9PEo3QU7TGCDolv6YZp1AncexKXgyQYYnQxmCM6lN40FQbI61K0FxV0Y3C3Dl2Y9PN4fgT5R1wM4cZJn5iUU8dfQjyYhnSWt8NBUwREDl51p7lakLs0oJzySLZG6fDPToBjfrk4rDXsRFRi9UBMcP3MWnyn40DW7RGfGMndaC4UUoMv/Dj3w== emiliano.heyns@iris-advies.com
```

is the same one you use on sourceforge, right? I made a minimal fork with another key and I was able to rsync with your commands.

**Comment by retorquere** [comment]
That is correct, same key.

**Comment by mwt** [comment]
I see. I emailed you the key and allowed_hosts that I tested with since I can at least confirm that this works.

If you add those as secrets, I can try a PR.

**Comment by retorquere** [comment]
Publish works, but install not. What is the public URL of the assets?

> I see. I emailed you the key and allowed_hosts that I tested with since I can at least confirm that this works.
> 
> If you add those as secrets, I can try a PR.

These are added, a PR would be great.

**Comment by retorquere** [comment]
PRs, if any, on the `matrix` branch please.

**Comment by mwt** [comment]
> Publish works, but install not. What is the public URL of the assets?

Right now, it's 
https://retorquere-test.mwt.me/apt-package-archive/
if you point your own hostnames at the server, that would work too.

**Comment by retorquere** [comment]
mwt is [live](https://github.com/retorquere/zotero-deb/runs/5629121260?check_suite_focus=true)!

**Comment by retorquere** [comment]
Is there a chat-like (signal, discord, etc) place where we could talk about the hosting?

**Comment by mwt** [comment]
Yeah. I just emailed you my phone number for signal. I also have Discord, mwt#1922, and I'm mwt on [libera.chat](https://libera.chat/).
