### ISSUE TITLE
Can I help push zotero-deb into the Zotero org's build process?

### ISSUE THREAD

**Issue by maxsu** [retorquere/zotero-deb#65]
I recently noticed that the zotero project doesn't publish debs or rpms for linux users and was wondering if I can help get those included in the build process! Could we map out your view of the current progress, unmet requirements, and blockers? I'd be happy to chat here, or in another channel, like email or the zotero dev mailing list.

So far I found your original [zotero-deb announcement](https://groups.google.com/g/zotero-dev/c/SL_l-ZKRbjU/m/8_QIw3W0CAAJ). I am supposing the blockers are on the zotero org side, and it may take some insistence to overcome them.

**Comment by retorquere** [comment]
I dunno -- I've facilitated the process where I could, but just spent about two weeks to get stable hosting going on my own, so I'm less inclined to put pressure on Zotero for this. Current state of things is pretty good, and I need to keep some hosting going in any case because I suspect Zotero will not host the jurism binaries (which I do).

RPMs are next on my todolist for hosting.

**Comment by maxsu** [comment]
Okay, sounds like getting RPMs up is the current priority. I'll close this issue for now. Can I join you on the RPM development?

**Comment by retorquere** [comment]
Oh please do. It's been a decade or two since I built them.

**Comment by maxsu** [comment]
Is there a current branch or repo, or would we port zotero-deb to rpm?

**Comment by retorquere** [comment]
The name of the project might have to change at some point, but I have made modifications that should allow the general infrastructure to be reused across packaging systems. the `rebuild` script checks what versions ought to be available, lays out the clients not yet build for the platform in a staging directory, and then defers to a platforms-specific library, in this case `apt.py`. Actual publishing is dealt with in the publish workflow -- there would likely be a separate workflow to publish rpms.

**Comment by maxsu** [comment]
Sounds great! I will send some preliminary PRs your way soon, and sketch a
plan of attack.

**Comment by retorquere** [comment]
Mind that the RPMs will need to be built on ubuntu, not a RH-derivative, as that's what GH offers. But building RPMs on ubuntu works.
