### ISSUE TITLE
Packages out of date

### ISSUE THREAD

**Issue by mirenradia** [retorquere/zotero-deb#68]
I'm not sure if the packages are supposed to auto update or if manual intervention is required but it seems the latest build of Zotero available in the repo is 6.0.1 but [the latest version is currently 6.0.4](https://www.zotero.org/support/changelog). Would it be possible to update it as I think some of the problems I'm having may be fixed in this latest version (according to the changelog)?

**Comment by retorquere** [comment]
It is supposed to aut-update, I'll get right on it.

**Comment by mirenradia** [comment]
Thanks!

**Comment by retorquere** [comment]
I've found & fixed the problem, thanks for reporting it
