### ISSUE TITLE
Invalid header

### ISSUE THREAD

**Issue by aw1231** [retorquere/zotero-deb#69]
I'm not sure if this is related to #68 but I am getting `Failed to fetch https://zotero.retorque.re/file/apt-package-archive/./InRelease  The HTTP server sent an invalid Content-Range header Bad header data [IP: 172.67.136.194 443]` when running apt update.

**Comment by retorquere** [comment]
Can you try to run `apt-get clean` and then retry?

**Comment by aw1231** [comment]
That worked. Apologies for the noise.

**Comment by retorquere** [comment]
No worries. I get this occasionally to, and I have no idea why.
