### ISSUE TITLE
Unable to install on Kubuntu 18.04

### ISSUE THREAD

**Issue by vincegre** [retorquere/zotero-deb#7]
Tried to install Zotero following tutorial here but when I try to do the apt install zotero it complains about an unresolvable dependency issue:

```
Les paquets suivants contiennent des dépendances non satisfaites :
 zotero : Dépend: libnss3-devlibnss3-dev mais il n'est pas installable
E: Impossible de corriger les problèmes, des paquets défectueux sont en mode « garder en l'état ».
```

What can I do ?

Thanks

**Comment by retorquere** [comment]
The repo is rebuilding at this exact moment. I'll respond here when it's done.

**Comment by vincegre** [comment]
> The repo is rebuilding at this exact moment. I'll respond here when it's done.

oh oki no problem ;) just let me know when it's done so I can test it again !

**Comment by retorquere** [comment]
The repos are back up.

**Comment by retorquere** [comment]
Oh wait what? My French isn't very good but that says that libnss-dev is duplicated? Hold on.

**Comment by vincegre** [comment]
Nope it says there is no installable version of libnss-dev and still the same after repo back up :(

**Comment by retorquere** [comment]
No I see the error, the package says it needs `libnss3-devlibnss3-dev` where it should say it needs `libnss3-dev`. Repo's are rebuilding again.

**Comment by retorquere** [comment]
Try again now (you'll need to `apt update` first)

**Comment by vincegre** [comment]
> No I see the error, the package says it needs `libnss3-devlibnss3-dev` where it should say it needs `libnss3-dev`. Repo's are rebuilding again.

ah yep good point, didn't notice the mispell in name of dependency ;) Thanks for so fast fix, installed with success now ;) Going to discover that tool and practices it ! thanks again for suck work ;)

**Comment by retorquere** [comment]
My work sucks? 😆
