### ISSUE TITLE
Local testing for rebuild process

### ISSUE THREAD

**Issue by maxsu** [retorquere/zotero-deb#71]
I'd like to write some tests to make possible to validate zotero-deb after refactoring. This helps contributors to feel more confident in their changes (eg, without a round trip to github actions.)

### Proposal: E2E test for rebuild.py
This should validate changes to the rebuild process. I've sketched this out in #70 

```diff
Pro:
+ Immediacy: Doesn't require breaking up rebuild.py into units

Con:
- Places extra load onto the zotero and jurism servers
- Current implementation doesn't strongly validate packages
```
### Proposal: Unit testing

This could better validate invariants of individual functions.

```diff
Pro:
+ Signals whether code is well factored
+ Faster to run than an E2E test

Con:
- Requires some refactoring of the code
```

**Comment by retorquere** [comment]
I've already merged the e2e tests. As long as you keep the built debs or the staging area there should be no significant impact on the zotero/jurism servers.

I'm OK with refactoring, as long as the diffs aren't too big.

**Comment by maxsu** [comment]
Sounds good!

I'll go ahead and close this issue. If/when I write unit tests I'll send a PR for review. Once the testing interface is more stable, I can document it in the Readme. 

Does that sound okay?
