### ISSUE TITLE
Updating in ubuntu 21.10

### ISSUE THREAD

**Issue by nquesada** [retorquere/zotero-deb#76]
Hi --- I am trying to update in ubuntu 21.10.

I've tried from within zotero to get

![image](https://user-images.githubusercontent.com/991946/163703812-01b30232-9748-4903-b9e6-abccb4aa863a.png)

and I also tried
`
sudo apt update
sudo apt upgrade
`
 but nothing get upgraded.

Thanks for any advice!

**Comment by retorquere** [comment]
The internal update doesn't work, as indeed the program location is not writable. What is the contents of `/etc/apt/sources.list.d/zotero.list` on your system?

**Comment by nquesada** [comment]
Hi @retorquere --- Thanks for your prompt reply. I get the following:
```bash
$ cat /etc/apt/sources.list.d/zotero.list
# deb https://github.com/retorquere/zotero-deb/releases/download/apt-get/ ./
```

**Comment by retorquere** [comment]
The location of the repo has moved, see https://github.com/retorquere/zotero-deb#readme for instructions on how to update

**Comment by nquesada** [comment]
I am still at loss. DO you mean that I need to update the contents of the file you mentioned above? Or that I need to reinstall? If the latter, will I loose the current contents? Thanks!

**Comment by retorquere** [comment]
You can just run the install.sh again; this will not touch your data or even the current installation of zotero, it will just tell Ubuntu where to get upgrades.

**Comment by retorquere** [comment]
(or your can indeed update that file, which is what install.sh does)

**Comment by nquesada** [comment]
Thanks! That worked.
