### ISSUE TITLE
2 simple questions

### ISSUE THREAD

**Issue by vuvlab** [retorquere/zotero-deb#8]
For Ubuntu, is curl the default function to download, while wget is what windows tends to use? or vice-versa. It was unclear which I should use. 

And I'm use to installing optional/user packages into /opt/Zotero directly. But your repo no longer installs to there. I end up having to modify the permissions of that install directory so that Zotero can automatically update. But since switching to your repo (from the old smathot/cogscinl repo), I can't locate the program install directory.  

  So could you put on the readme, the default install directory, or maybe shift to, or give option of using /opt/zotero for th eprogram install?
thanks

**Comment by retorquere** [comment]
It doesn't matter which you use -- if you have `curl`, you can use that, if you have `wget`, that's also fine. On Ubuntu, I usually use `curl`.

My repo has never installed to `/opt` -- ISTR that `opt` is for user-managed packages by convention, and that `.debs` usually install in `/usr/lib`, and the debs put zotero in `/usr/lib/zotero`.

Debs can't really sensibly do configurable installation paths, sorry.

**Comment by retorquere** [comment]
I've updated the readme; on Ubuntu, you can also see where packages are installed using `dpkg -L zotero`.
