### ISSUE TITLE
error when upgrading Ubuntu 

### ISSUE THREAD

**Issue by davdent** [retorquere/zotero-deb#80]
I am trying to upgrade Ubuntu from 21.10 to 22.04 and I get the following error and the upgrading process won't go any further: 

err https://apt.retorque.re/file/zotero-apt ./ inrelease

I realise that this closely resembles another issue posted recently, but that does not help me (being rather clueless about managing my Linux system) know how to fix this issue so that I can continue the upgrade. Any assistance you can provide on this would be appreciated.

**Comment by retorquere** [comment]
If you run

```
curl -sL https://raw.githubusercontent.com/retorquere/zotero-deb/master/install.sh | sudo bash
```

your installation will be pointed to the new location. No need to do anything else, after this you will be able to update as usual.

**Comment by retorquere** [comment]
The question is why your file system is mounted read-only. The only mentions I could find of this point to filesystem corruption. What does 

```
sudo dmesg | grep EXT4
```

show?

**Comment by davdent** [comment]
[    1.890751] EXT4-fs (sda5): mounted filesystem with ordered data mode. Opts: (null). Quota mode: none.
[    2.234797] EXT4-fs (sda5): re-mounted. Opts: errors=remount-ro. Quota mode: none.

In any case, eventually, the installation did point to the new location and everything installed correctly and seems to be working well. Thank you!
