### ISSUE TITLE
PSA: if you get update errors, re-run the repo install

### ISSUE THREAD

**Issue by retorquere** [retorquere/zotero-deb#81]
See https://github.com/retorquere/zotero-deb#readme

> If you are getting errors, **please re-run install.sh** or see the instructions below to re-install manually. I have had to restructure the repos. I apologize, but it was a necessary simplification. Simply re-running the install is all that is required.

**Comment by regtm** [comment]
Just to confirm, this is regarding the following source?

`Failed to fetch https://zotero.retorque.re/file/apt-package-archive/./InRelease`

**Comment by retorquere** [comment]
Among other files, yes. But I can download that url without issue. Do you have the same problem when you download using curl of your browser?

**Comment by regtm** [comment]
I can download via browser/curl as well, though apt mentions an invalid content-range header:
`W: Failed to fetch https://zotero.retorque.re/file/apt-package-archive/./InRelease  The HTTP server sent an invalid Content-Range header Bad header data [IP: 172.67.136.194 443]
`

**Comment by retorquere** [comment]
https://askubuntu.com/questions/41136/installing-via-apt-get-install-always-give-the-http-server-sent-an-invalid-cont maybe?

**Comment by regtm** [comment]
Ubuntu 22.04.2 LTS

Clearing the cache indeed solved it. Thanks a lot for your work!
