### ISSUE TITLE
extension on chrome

### ISSUE THREAD

**Issue by jocelinkisenga** [retorquere/zotero-deb#82]
hello big team , i got a problem while helping my sister when using zotero for her practice. 
In fact they where told to make some research on pubmed so that they could write an collection. I saw you have added an extension for chrome scholar search, but she is familiar with our simple google research, so have difficult to share her research  because the icon zotero does'nt not pop up on simple research. can't be there an suggestion?

**Comment by retorquere** [comment]
no big team, just me. Are you trying to install Zotero? On what operating system are you trying to install it?

**Comment by jocelinkisenga** [comment]
I have already installed it on my Linux deepin

**Comment by retorquere** [comment]
Then I don't know what you are asking, sorry. This package only deals with installing Zotero, any questions about zotero or its plugins are handled on the zotero forums.
