### ISSUE TITLE
Cloudflare messing with Packages.bz2

### ISSUE THREAD

**Issue by mwt** [retorquere/zotero-deb#83]
Packages.bz2 has a checksum mismatch when downloading with anything other than apt. I think it might be due to Cloudflare. It's messing with my mirror and it seems to be a recent phenomenon. You can see the mismatch by doing:

```sh
> curl -s https://zotero.retorque.re/file/apt-package-archive/Release | grep -m 1 Packages.bz2
1f3ab3c43b408e35396c832d265bc76b             4676 Packages.bz2
```
```sh
> curl -s https://zotero.retorque.re/file/apt-package-archive/Packages.bz2 | md5sum
50e9e3bbe35b8ee72acf943ff8f887ff  -
```

It seems that the one being served is 20 bytes smaller than the one that you made. I suspect that Cloudflare optimization is at fault. I'm not sure how to download the original unmodified version. The obvious solution is to set `Cache-Control: no-transform`. I'm not sure if you can do this with Backblaze (I imagine not). I think it can be done with Cloudflare transform rules.

**Comment by retorquere** [comment]
This is what I get:

```
> curl -s https://zotero.retorque.re/file/apt-package-archive/Release | grep -m 1 Packages.bz2
 aae1ef330f1b104cd3c9f09f68f7f84d             4681 Packages.bz2
> curl -s https://zotero.retorque.re/file/apt-package-archive/Packages.bz2 | md5sum
aae1ef330f1b104cd3c9f09f68f7f84d  -
```

and the repo and packages are reinstalled on a clean VM (on [github actions](https://github.com/retorquere/zotero-deb/actions)) every two hours, and that has ran green for a while now. If it were a problem on CFs end, I figure I would have seen this on my system and GH actions. Do you get a different mirror than I am? I am getting 

```
Non-authoritative answer:
Name:	zotero.retorque.re
Address: 104.21.54.76
Name:	zotero.retorque.re
Address: 172.67.136.194
```

and I'm getting the same from GH actions:

```
Server:		127.0.0.53
Address:	127.0.0.53#53
Non-authoritative answer:
Name:	zotero.retorque.re
Address: 104.21.54.76
Name:	zotero.retorque.re
Address: 172.67.136.194
Name:	zotero.retorque.re
Address: 2606:4700:3031::6815:364c
Name:	zotero.retorque.re
Address: 2606:4700:3033::ac43:88c2
 aae1ef330f1b104cd3c9f09f68f7f84d             4681 Packages.bz2
aae1ef330f1b104cd3c9f09f68f7f84d  -
```

so I'm not sure CF is the problem.
