### ISSUE TITLE
Woud you consider submitting this packaging to Debian ?

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [retorquere/zotero-deb#84]
This packaging might be submitted to Debian, thus easing its use in *all* Debian-based distributions...

Would you consider it ?

**Comment by retorquere** [comment]
I have actually tried it, but it's out of my reach. Debian doesn't allow packages that just bundle binaries, and zotero's own build process downloads binaries from Firefox. You're required to build on their build infra, and their build infra blocks internet connections to prevent things like this. It'd require either building the entire binary chain myself, or create a wrapper package that does the download during install, like Java, which was fragile when I had it.

**Comment by EmmanuelCharpentier** [comment]
I see... Too bad.

Woud you consider setting up a "Debian repository", configurable as an apt source ?

**Comment by retorquere** [comment]
I already have an apt repo? The current Readme explains how to add the repo to your apt setup.

**Comment by EmmanuelCharpentier** [comment]
> I already have an apt repo? The current Readme explains how to add the repo to your apt setup.

Wups ! I didn't see that. I'll try it.

Thanks a *lot* !
