### ISSUE TITLE
Please install binary in /usr/bin, not /usr/local/bin

### ISSUE THREAD

**Issue by MHellmund** [retorquere/zotero-deb#85]
SInce zotero-deb installs everything else in /usr/lib or /usr/share and not in /usr/local/lib or /usr/local/share, the binary should also go to /usr/bin/zotero. 

(We have nearly a hundred Debian machines which mount /usr/local read-only from a server)  

Thank you very much!

**Comment by retorquere** [comment]
When you say "also", do you mean "like the rest of the package" or "in /usr/local/bin, and also in /usr/bin"?

**Comment by MHellmund** [comment]
Sorry for the unclear wording.  I mean ""like the rest of the package". 
See also https://www.debian.org/doc/debian-policy/ch-opersys.html , section 9.1.2

**Comment by MHellmund** [comment]
Ypur speed is very impressive!
Thanks alot!
