### ISSUE TITLE
ERROR : E: Unable to locate package zotero

### ISSUE THREAD

**Issue by AdrienL88** [retorquere/zotero-deb#86]
Hi ! I'm sorry, I'm not sure I could post this here but I really don't understand my issue about installing Zotero on a Chromebook 

`` ~$ curl -sL https://raw.githubusercontent.com/retorquere/zotero-deb/master/install.sh | sudo bash
sudo apt update
sudo apt install zotero
Zotero is only available for architectures i686 and x86_64
Hit:1 https://deb.debian.org/debian bullseye InRelease                          
Hit:2 https://deb.debian.org/debian bullseye-updates InRelease                  
Ign:3 https://storage.googleapis.com/cros-packages/107 bullseye InRelease
Hit:4 https://deb.debian.org/debian-security bullseye-security InRelease
Hit:5 https://storage.googleapis.com/cros-packages/107 bullseye Release
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
5 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package zotero

Could you indicate me what is the source of this error ?
Thank you !

**Comment by retorquere** [comment]
> Could you indicate me what is the source of this error ? Thank you !

~$ curl -sL https://raw.githubusercontent.com/retorquere/zotero-deb/master/install.sh | sudo bash
sudo apt update
sudo apt install zotero

**Zotero is only available for architectures i686 and x86_64**

Hit:1 https://deb.debian.org/debian bullseye InRelease
Hit:2 https://deb.debian.org/debian bullseye-updates InRelease
Ign:3 https://storage.googleapis.com/cros-packages/107 bullseye InRelease
Hit:4 https://deb.debian.org/debian-security bullseye-security InRelease
Hit:5 https://storage.googleapis.com/cros-packages/107 bullseye Release
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
5 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package zotero
