### ISSUE TITLE
wrong dependence in new version?

### ISSUE THREAD

**Issue by aytvill** [retorquere/zotero-deb#87]
_apt subsystem_ says my zotero could be upgraded

> $ apt list --upgradable -a
Listing... Done
zotero/unknown 6.0.19 amd64 [upgradable from: 6.0.18]
zotero/unknown,now 6.0.18 amd64 [installed,upgradable to: 6.0.19]
zotero/unknown 6.0.16 amd64
zotero/unknown 6.0.15 amd64
zotero/unknown 6.0.14 amd64

but normal _apt upgrade_ doesn't do anything

when I manually invoke _apt install zotero_ , it complains

> $ sudo apt install zotero
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

> The following packages have unmet dependencies:
 zotero : Depends: libgdk-pixbuf-2.0-0 but it is not installable
E: Unable to correct problems, you have held broken packages.

when I check presence of _libgdk-pixbuf_ it says, I have it present (and packages depend on it), but name has dashes somewhat different

> $ apt-cache show libgdk-pixbuf2.0-
libgdk-pixbuf2.0-0       libgdk-pixbuf2.0-bin     libgdk-pixbuf2.0-common  libgdk-pixbuf2.0-dev     libgdk-pixbuf2.0-doc

could you please check packaging, whether it has proper name of that library, when it made last increment?

**Comment by retorquere** [comment]
What OS are you installing this on?

**Comment by HenriVDD** [comment]
Hello I have the same issue (on Ubuntu 20.04)

I think as @aytvill just said it's a dash issue
zotero : Depends: libgdk-pixbuf-2.0-0 (E: Package 'libgdk-pixbuf-2.0-0' has no installation candidate)
existing package : libgdk-pixbuf2.0-0 (libgdk-pixbuf2.0-0 is already the newest version (2.40.0+dfsg-3ubuntu0.4).)

No "-" between libgdk-pixbuf and 2.0-0 for the dependencies

Hope this help
Best,

**Comment by retorquere** [comment]
Can you try installing zotero_6.0.19-1 ?

The packages were built on ubuntu-latest, the packages are now built on 20.04, so that should pull in the versions you need. Bit of a pain that 22.04 has changed the versioning scheme.

**Comment by HenriVDD** [comment]
I just sudo apt update and upgrade and it worked this time. Thanks for the fix !

**Comment by retorquere** [comment]
@aytvill ?

**Comment by aytvill** [comment]
yes, I have also 20.04 for variety or reasons
> $ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal

also for me issue is closed - I have re-enabled apt source and installed it, and it works now, **thank you**

below is apt-cache output

>$ apt-cache show zotero
Package: zotero
Architecture: amd64
Version: 6.0.19-1
Priority: optional
Section: Office
Maintainer: (email taken off by @aytvill for privacy reasons)
Depends: gnupg, libasound2, libatk1.0-0, libc6, libcairo-gobject2, libcairo2, libdbus-1-3, libdbus-glib-1-2, libfontconfig1, libfreetype6, libgdk-pixbuf2.0-0, libglib2.0-0, libgtk-3-0, libharfbuzz0b, libpango-1.0-0, libpangocairo-1.0-0, libstdc++6, libx11-6, libx11-xcb1, libxcb-shm0, libxcb1, libxcomposite1, libxcursor1, libxdamage1, libxext6, libxfixes3, libxi6, libxrandr2, libxrender1, libxtst6
Filename: ./zotero_6.0.19-1_amd64.deb
Size: 72201694
MD5sum: b844eb6c082f026e43971a44d4fffc03
SHA1: ed0a33023189974c572b07f6f909dd3d0c468c40
SHA256: 554b4c7db05c152f0a7b573d0d507ded16062229d1d808dd7c51a30471fc157f
SHA512: 325885424cf036e0dd3498ff9464215d07ab9cce1a013a41e8415c4bbe702822f72db11b104a18ec2b8b5b0a920ffcbe257aec84af2bacfcf861b30b51bf6531
Description: Zotero is a free, easy-to-use tool to help you collect, organize, cite, and share research
Description-md5: 7a815968c7a14103b6521be0664add48

>Package: zotero
Architecture: amd64
Version: 6.0.18
Priority: optional
Section: Office
Maintainer: (email taken off by @aytvill for privacy reasons)
Depends: gnupg, libasound2, libatk1.0-0, libc6, libcairo-gobject2, libcairo2, libdbus-1-3, libdbus-glib-1-2, libfontconfig1, libfreetype6, libgdk-pixbuf2.0-0, libglib2.0-0, libgtk-3-0, libharfbuzz0b, libpango-1.0-0, libpangocairo-1.0-0, libstdc++6, libx11-6, libx11-xcb1, libxcb-shm0, libxcb1, libxcomposite1, libxcursor1, libxdamage1, libxext6, libxfixes3, libxi6, libxrandr2, libxrender1, libxtst6
Filename: ./zotero_6.0.18_amd64.deb
Size: 72149838
MD5sum: cd423a5eeec45f1910e8de34b6e4687d
SHA1: 14a3474da93b7bd22ab74e402cdbc2bb784211e6
SHA256: acc0db280d2ba4d01d2449fff1de0a1ea7271ab420ff326ee1127735353dff57
SHA512: cfb74bdb13b021bf390f28775211e093cf190995fbb5d0d338b20120698519104ec4dc38cb21f5257c4cbcf1a08fba134d72d7e49302f4ede8862a0487a0a743
Description: Zotero is a free, easy-to-use tool to help you collect, organize, cite, and share research
Description-md5: 7a815968c7a14103b6521be0664add48

>Package: zotero
Architecture: amd64
Version: 6.0.16
Priority: optional
Section: Office
Maintainer: (email taken off by @aytvill for privacy reasons)
Depends: gnupg, libasound2, libatk1.0-0, libc6, libcairo-gobject2, libcairo2, libdbus-1-3, libdbus-glib-1-2, libfontconfig1, libfreetype6, libgdk-pixbuf2.0-0, libglib2.0-0, libgtk-3-0, libharfbuzz0b, libpango-1.0-0, libpangocairo-1.0-0, libstdc++6, libx11-6, libx11-xcb1, libxcb-shm0, libxcb1, libxcomposite1, libxcursor1, libxdamage1, libxext6, libxfixes3, libxi6, libxrandr2, libxrender1, libxtst6
Filename: ./zotero_6.0.16_amd64.deb
Size: 72148978
MD5sum: 63c442f40942cc7be3cec02eb7efb57a
SHA1: 1e144677bed17673df70ef86b1175096b545ca71
SHA256: 56e1e838fcac95e6b72a57817ff033cf892c4cfe803ca3c1143ccb069621ba80
SHA512: e8bb2bb1b98f8884ab2a21034f164da1310416b8e2e6301c0862c3f1dd5515cd935e2360bdaea17d324a7f7e70463edacdec5af4f4f8002096feac40699c3e64
Description: Zotero is a free, easy-to-use tool to help you collect, organize, cite, and share research
Description-md5: 7a815968c7a14103b6521be0664add48

>Package: zotero
Architecture: amd64
Version: 6.0.15
Priority: optional
Section: Office
Maintainer: (email taken off by @aytvill for privacy reasons)
Depends: gnupg, libasound2, libatk1.0-0, libc6, libcairo-gobject2, libcairo2, libdbus-1-3, libdbus-glib-1-2, libfontconfig1, libfreetype6, libgdk-pixbuf2.0-0, libglib2.0-0, libgtk-3-0, libharfbuzz0b, libpango-1.0-0, libpangocairo-1.0-0, libstdc++6, libx11-6, libx11-xcb1, libxcb-shm0, libxcb1, libxcomposite1, libxcursor1, libxdamage1, libxext6, libxfixes3, libxi6, libxrandr2, libxrender1, libxtst6
Filename: ./zotero_6.0.15_amd64.deb
Size: 72103158
MD5sum: 85724f005b97d2a0b6fe42396a632c5c
SHA1: e47b05406243fe5bbc144b6e6ef0663d4cca86ec
SHA256: 9a8754c65266ca064ae7720e4c059500b29a2dc36a058cbf0658a4f3cf4a7c68
SHA512: b5997fb42f9099907749a5398a5ba951e0a2071b94dc77aa5337c7fc6497a03b4e74428b8a721010851eed0ba859e1a49392bbc66dbc41743880002767114a0a
Description: Zotero is a free, easy-to-use tool to help you collect, organize, cite, and share research
Description-md5: 7a815968c7a14103b6521be0664add48

>Package: zotero
Architecture: amd64
Version: 6.0.14
Priority: optional
Section: Office
Maintainer: (email taken off by @aytvill for privacy reasons)
Depends: gnupg, libasound2, libatk1.0-0, libc6, libcairo-gobject2, libcairo2, libdbus-1-3, libdbus-glib-1-2, libfontconfig1, libfreetype6, libgdk-pixbuf2.0-0, libglib2.0-0, libgtk-3-0, libharfbuzz0b, libpango-1.0-0, libpangocairo-1.0-0, libstdc++6, libx11-6, libx11-xcb1, libxcb-shm0, libxcb1, libxcomposite1, libxcursor1, libxdamage1, libxext6, libxfixes3, libxi6, libxrandr2, libxrender1, libxtst6
Filename: ./zotero_6.0.14_amd64.deb
Size: 72089478
MD5sum: ab94b60d25f790a216501879dd5e3a64
SHA1: 2ae6dfb26a4639e91a818b0b1de3f9e1ac96303b
SHA256: 457e2056cab167be090cd2c3ae85372a4389e7a1d07fa149e58def44979bf6d1
SHA512: 23c85402a8c7ecdd34974e94a196039cf7b14543a230e5a61967271fe5128de59713f7c887bbbc9fce93af72c2993f076b38bfd2d53ec95e3c9aa2b7d770f0af
Description: Zotero is a free, easy-to-use tool to help you collect, organize, cite, and share research
Description-md5: 7a815968c7a14103b6521be0664add48
