### ISSUE TITLE
versions don't match

### ISSUE THREAD

**Issue by allefeld** [retorquere/zotero-deb#88]
I have configured the repository and then installed the zotero package with the latest version, 6.0.26. Zotero can be started, but if I select *Help* / *About Zotero*, it says 6.0.20. That is the same version I had previously installed manually from the tarball.

**Comment by retorquere** [comment]
The tarball install may have installed the launcher shortcut in your home directory, which takes precedence over the global install.

**Comment by retorquere** [comment]
I think the desktop file (the launcher shortcut) from the tarball will be in `~/.local/share/applications`. If you remove the Zotero desktop file there, it should fall back to the one the deb package installs in `/usr/share/applications/`. You can start the deb-installed zotero manually by starting `/usr/lib/zotero/zotero`.

**Comment by allefeld** [comment]
That did it, thanks!

**Comment by retorquere** [comment]
The debs don't install anything in anyone's home directory. I don't know how the one in `~/.local` reappered, but it's not from the deb package.
