### ISSUE TITLE
Why two different .desktop files ?

### ISSUE THREAD

**Issue by ngirard** [retorquere/zotero-deb#9]
After installing `https://github.com/retorquere/zotero-deb/releases/download/global-menu ./ zotero 5.0.71`, I noticed the package contains two different `.desktop` files:

![Screenshot_20190721_113615](https://user-images.githubusercontent.com/98098/61589550-c71f8600-abab-11e9-8d23-92860fe1be69.png)

**Comment by retorquere** [comment]
The one in /usr/lib/zotero is just the one packaged by the official zotero binaries. New packages are building that removes this one.
