### ISSUE TITLE
(Serious) problems with a freshly-installed repo version

### ISSUE THREAD

**Issue by EmmanuelCharpentier** [retorquere/zotero-deb#90]
I have a communication problem and a display update problem with a freshly-installed repo version (replacing a hand-installed one).

My motivation was the communication problem (constated with the hand-installed version). The display problem seems new.

Setup : 
- Debian testing
- LibreOffice as from Debian testing
- Zotero (6.0.26) installed today (2023-08-17) from the repo added via your script.
- LibreOffice plugin (6.0.3) reinstalled systemwide (using `sudo lowriter` to reinstall for all users, using `/usr/lib/zotero/extensions/zoteroOpenOfficeIntegration@zotero.org/install/Zotero_OpenOffice_Integration.oxt`)

Symptoms : 
- Communication problem :
    - Zotero opens fine and retirieve my daatabase (local library + 3 shared libraries)
    - I can't open the plugin's `Set Zotero preferences` : trying tis opens a dialog box stating `LibreOffice could not communicate with Zotero. Please ensure Zotero is open and set to an online state and try again.`
- Display/update problem :
    - Creating a new collection in one of the shared libraries is inefficient : command is accepted but the collection "never" appears.
    - Ditto for a new collection in the local library.
    - However, closing Zotero then reopening it shows the newly created libraries.
    - Adding a reference in the local library new collection (via the Chromium plugin) is apprently inefficient.
    - However, selecting another collection then reselecting the new library shows that the reference has indeed been added.
    - Ditto for the shared library.

Are these problems specific to your repo, or should they be reported directly to Zotero ?

Sincerely yours,

**Comment by retorquere** [comment]
The problem that also appears in the hand-installed one should be reported to Zotero. The binaries in the deb are just the official binaries that my builds download as they are deb-packaged; I don't build the Zotero binaries myself.

If that problem is solved, and then the other problem remains, I can look into that, but given that you also have problems with the hand-install, that might indicate some incompatibility between your system and the Zotero release, and I'd prefer it if that were settled first.

**Comment by EmmanuelCharpentier** [comment]
Thanks ! I'll do that.Le 17 août 2023 16:32, Emiliano Heyns ***@***.***> a écrit :
The problem that also appears in the hand-installed one should be reported to Zotero. The binaries in the deb are just the official binaries that my builds download as they are deb-packaged; I don't build the Zotero binaries myself.
If that problem is solved, and then the other problem remains, I can look into that, but given that you also have problems with the hand-install, that might indicate some incompatibility between your system and the Zotero release, and I'd prefer it if that were settled first.

**Comment by EmmanuelCharpentier** [comment]
Following suggestions made on the Zotero forum, I disabled BetterBibTeX, whioch restored normal Zotero behaviour. The ball seems on your side (but not on your side of this script !)  ;-).

Do you need another issue on the BetterBibtex Github side ?

**Comment by retorquere** [comment]
Yes.

**Comment by EmmanuelCharpentier** [comment]
> Yes.

[Done](https://github.com/retorquere/zotero-better-bibtex/issues/2623).
