### ISSUE TITLE
First mirror is offline

### ISSUE THREAD

**Issue by visika** [retorquere/zotero-deb#94]
https://zotero-deb.mirror.ioperf.eu/ is not reachable.
Running the install script and trying to install zotero results in error 500.

**Comment by retorquere** [comment]
It looks like the primary repo is down. I've contacted backblaze support.

**Comment by cohnt** [comment]
I'm getting the following error when I run `apt update`, is this related?

```
Err:2 https://zotero.retorque.re/file/apt-package-archive ./ InRelease
  The HTTP server sent an invalid Content-Range header Bad header data
```

**Comment by retorquere** [comment]
Not related, no. The bucket has been back for a long time now.

@cohnt I can't replicate this locally, and the tests run every two hours on github, and these are also [all green](https://github.com/retorquere/zotero-deb/actions/workflows/publish.yaml). Try running `sudo apt-get clean` and after that try `apt update` again. If that doesn't resolve the problem, please open a new issue.
