### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by webysther** [retorquere/zotero-deb#95]
Hi, just to say thanks, I have created the docker image and your code was really important to make this happen: https://hub.docker.com/r/webysther/zotero

**Comment by retorquere** [comment]
You're welcome. With this setup it seems you keep zotero's auto-update on yeah? Is that intended?

**Comment by webysther** [comment]
> You're welcome. With this setup it seems you keep zotero's auto-update on yeah? Is that intended?

No, I don't have experience with Zotero, i just look around and don't find a solution to use in that way, if you have suggestions or if you want to create a repository with that code, no problem.

How turn off? Do you have more suggestions?

**Comment by retorquere** [comment]
https://github.com/retorquere/zotero-deb/blob/master/apt.py#L96
