### ISSUE TITLE
Broken `apt` repository `https://mirror.mwt.me/zotero/deb`

### ISSUE THREAD

**Issue by maxkratz** [retorquere/zotero-deb#99]
For a few hours, the `apt` repository https://mirror.mwt.me/zotero/deb seems to be broken:

```
sudo apt-get upgrade --download-only 
[...]
Need to get 72,4 MB/336 MB of archives.
After this operation, 4.406 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://mirror.mwt.me/zotero/deb ./ zotero 6.0.35 [72,4 MB]
Err:1 https://mirror.mwt.me/zotero/deb ./ zotero 6.0.35
  File has unexpected size (72404592 != 72403272). Mirror sync in progress? [IP: 2606:4700:20::681a:c05 443]
  Hashes of expected file:
   - SHA512:3091f569724af0afba4a5d7aed9c5c3a644a3b6b2593c1f7ffa619898c39d6e43c30c282d2036a1fdc5e07b0a4a12bb8e345577b399a517a94910b0efbf58a03
   - SHA256:df7443b98e7645b0536c47b612eb8bd250bddd91126935e1d92d1ef8680a674f
   - SHA1:c27d83ec8e67101640d6649239f18be165eb202a [weak]
   - MD5Sum:74453931d9144517098345a18ea4fa01 [weak]
   - Filesize:72403272 [weak]
E: Failed to fetch https://mirror.mwt.me/zotero/deb/./zotero_6.0.35_amd64.deb  File has unexpected size (72404592 != 72403272). Mirror sync in progress? [IP: 2606:4700:20::681a:c05 443]
   Hashes of expected file:
    - SHA512:3091f569724af0afba4a5d7aed9c5c3a644a3b6b2593c1f7ffa619898c39d6e43c30c282d2036a1fdc5e07b0a4a12bb8e345577b399a517a94910b0efbf58a03
    - SHA256:df7443b98e7645b0536c47b612eb8bd250bddd91126935e1d92d1ef8680a674f
    - SHA1:c27d83ec8e67101640d6649239f18be165eb202a [weak]
    - MD5Sum:74453931d9144517098345a18ea4fa01 [weak]
    - Filesize:72403272 [weak]
E: Some files failed to download
```

**Comment by retorquere** [comment]
Does the primary still work for you? I need to know whether the primary is broken and poisoning the mirror, or whether it's the mirror itself that is broken.

**Comment by maxkratz** [comment]
> Does the primary still work for you?

If you mean `https://zotero.retorque.re/file/apt-package-archive` with "primary" then yes, this apt repository is also broken for me.

The second URL mentioned in the README.md seems to be unavailable; for this, I opened another issue: https://github.com/retorquere/zotero-deb/issues/98

**Comment by retorquere** [comment]
I'm not sure what's going wrong. I can't replicate the problem on my own system (which is my dev system, so that could be polluted) or in the [github action](https://github.com/retorquere/zotero-deb/actions/runs/8204469513/job/22439278110) which runs in a pristine environment every two hours. Thing is, I *did* make changes last night.

If I download https://zotero.retorque.re/file/apt-package-archive/Packages and https://zotero.retorque.re/file/apt-package-archive/zotero_6.0.35_amd64.deb, I do get consistent file sizes and hashes. Does `sudo apt-get clean` change anything for you?

**Comment by maxkratz** [comment]
> The second URL mentioned in the README.md seems to be unavailable; for this, I opened another issue: #98

I'm sorry about my mistake: I meant the first URL explicitly mentioned.



> I'm not sure what's going wrong. I can't replicate the problem on my own system (which is my dev system, so that could be polluted) or in the [github action](https://github.com/retorquere/zotero-deb/actions/runs/8204469513/job/22439278110) which runs in a pristine environment every two hours. Thing is, I _did_ make changes last night.
> 
> If I download https://zotero.retorque.re/file/apt-package-archive/Packages and https://zotero.retorque.re/file/apt-package-archive/zotero_6.0.35_amd64.deb, I do get consistent file sizes and hashes. Does `sudo apt-get clean` change anything for you?

`sudo apt-get clean` did not help on my (first) system. Nevertheless, I got curious and set up a vanilla Debian 12 VM and succesfully installed `zotero` via your `apt` repository.

Seems like this weird behaviour is an issue of my (host) system ...

**Comment by maxkratz** [comment]
Update: Now I got the same error on another (host) system. I do not have a clue why.

**Comment by retorquere** [comment]
What OS is on this system? I'll try setting one up in virtualbox.

**Comment by maxkratz** [comment]
> What OS is on this system? I'll try setting one up in virtualbox.

Both systems that show the error are running Pop!_OS 22.04 (with an additional `nala` frontend for `apt` installed, but I think the latter makes no difference).

(Vanilla Debian 12 is still fine.)

**Comment by retorquere** [comment]
Install and runs without a hitch on Pop!_OS 22.04 (using `apt`, I'm not familiar with `nala`).

**Comment by retorquere** [comment]
Maybe  try setting up the repo anew?

```
curl -sL https://raw.githubusercontent.com/retorquere/zotero-deb/master/install.sh | sudo bash
```

(or doing the steps by hand if you want to have more control -- encouraged by not required)

This will have no effect on other stuff on your system, it will just tell `apt` anew how to contact the repo, and what GPG key to use for verification. 

Although I don't know how you'd get different file sizes in the first place, so to be honest I don't see why this would fix it.

**Comment by maxkratz** [comment]
Thanks for the hint with the re-configuration of the apt repo.

Interestingly, I didn't get as far as trying it out. Today, both of my Pop!_OS 22.04 systems were able to download and update `zotero` to the latest version with no issue whatsoever.

Weird behavior ...

**Comment by retorquere** [comment]
I honestly don't know what could be the cause of this. I have been working on the packaging code this weekend but it didn't seem to affect any of the systems I used for testing.
